### ISSUE TITLE
Add `--no-color` as a global option and logWIthoutColor feature

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#100]
For logging, allow logging without color.

**Comment by cobrabr** [comment]
@ferventcoder -- quick question related to colors: is it possible to include an option somewhere to remove the `-NoProfile` command-line parameter from the PowerShell calls? 

I'm using a different color scheme on my Command Prompt (I'm using [ConEmu](https://conemu.github.io/)), and because of that, using PowerShell's default color scheme makes the progressbar almost invisible -- something I fixed by changing the colors on my profile config. Before the new Choco, I used to edit chocolatey.cmd and remove the `-NoProfile` from the `powershell.exe` call, but now I can't do that anymore... :)

Thanks!

**Comment by ferventcoder** [comment]
@cobrabr It might be. Here's the rub - I'm removing calling PowerShell as an external process completely. See #8.

I'm also using ConEmu. :)

**Comment by ferventcoder** [comment]
@cobrabr what this means is that the progress bar will no longer be the one you see, but a better one implemented right in line. Something closer to what you see with brew.

**Comment by cobrabr** [comment]
@ferventcoder Oh... I guess that solves it, then. :smile: I'm OK with waiting for the Powershell-less version, then.

**Comment by ferventcoder** [comment]
#1378 has a good workaround on this.

**Comment by ferventcoder** [comment]
This is good to go for v0.10.9.
