### ISSUE TITLE
Promote the use of Write-Information for info messages (and provide a shim for PS<5.0)

### ISSUE THREAD

**Issue by jberezanski** [chocolatey/choco#1024]
Microsoft has recognized the [limitations of Write-Host](http://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/) and has provided in PowerShell 5 [the new Information stream](https://blogs.technet.microsoft.com/heyscriptingguy/2015/07/04/weekend-scripter-welcome-to-the-powershell-information-stream/), which behaves like the existing streams (Verbose, Warning etc.), so it can be redirected, can be controlled via a dedicated preference variable and does not require any special host support (works on all hosts). The built-in way to write to this stream is the new `Write-Information` cmdlet.

I suggest we:
1) promote using Write-Information for general logging in package automation scripts,
2) for compatibility with older PowerShell, provide a Write-Information helper that delegates to Microsoft.PowerShell.Utility\Write-Information on PowerShell 5+ (similar to how it was done [in PS choco](https://github.com/chocolatey/chocolatey/blob/master/src/helpers/functions/Write-Host.ps1)) and uses Write-Host on PowerShell <= 4.

**Comment by ferventcoder** [comment]
We can only promote that use if we also have an extension package that serves as a polyfill for older versions of Chocolatey.

**Comment by jberezanski** [comment]
OK, so you're saying that each package using that function should depend on the new extension package?
Why not use the same approach as with other features added to Chocolatey, i.e. require the package to depend on a minimum version of Chocolatey?

**Comment by mvonballmo** [comment]
It's been over six years since this issue was opened, but I've noticed that Write-Information is the only message type that is _never_ captured by the log output.

Does that sound right? Or do I have something misconfigured?

I made a test script:

```powershell
    Write-Debug "Merhaba: DEBUG MESSAGE FROM TEST PACKAGE"
    Write-Verbose "Merhaba: VERBOSE MESSAGE FROM TEST PACKAGE"
    Write-Information "Merhaba: INFO MESSAGE FROM TEST PACKAGE"
    Write-Warning "Merhaba: WARNING MESSAGE FROM TEST PACKAGE"
    Write-Error "Merhaba: ERROR MESSAGE FROM TEST PACKAGE"
    Write-Host "Merhaba: HOST MESSAGE FROM TEST PACKAGE"
    Write-Output "Merhaba: OUTPUT MESSAGE FROM TEST PACKAGE"
```

The output captured in the choco.summary.log was:

```txt
2023-02-08 07:58:45,909 25972 [INFO ] - VERBOSE: Merhaba: VERBOSE MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:45,942 25972 [WARN ] - WARNING: Merhaba: WARNING MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:45,965 25972 [ERROR] - Merhaba: ERROR MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:46,010 25972 [INFO ] - Merhaba: HOST MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:46,041 25972 [INFO ] - Merhaba: OUTPUT MESSAGE FROM TEST PACKAGE
```

The output captured in the chocolatey.log was:

```txt
2023-02-08 07:58:45,906 25972 [DEBUG] - Merhaba: DEBUG MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:45,909 25972 [INFO ] - VERBOSE: Merhaba: VERBOSE MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:45,942 25972 [WARN ] - WARNING: Merhaba: WARNING MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:45,965 25972 [ERROR] - Merhaba: ERROR MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:46,010 25972 [INFO ] - Merhaba: HOST MESSAGE FROM TEST PACKAGE
2023-02-08 07:58:46,041 25972 [INFO ] - Merhaba: OUTPUT MESSAGE FROM TEST PACKAGE
```

**Comment by vexx32** [comment]
Write-Information by default in PowerShell is not written to the host like verbose, warning, or error are. To make that work, you'd need to add `-InformationAction Continue` onto your Write-Information call.

Additionally, choco can't pick up the information stream directly currently as for compatibility reasons we have historically only built against the v2 version of the PowerShell System.Management.Automation assembly. In order to explicitly collect the Information stream data directly when it is not shown to the host, we would need to build against a minimum of version 5.1 of the System.Management.Automation assembly and remove support for earlier PowerShell versions.

**Comment by mvonballmo** [comment]
@vexx32: thanks very much for the detailed response. This is eminently reasonable and I understand the reasoning behind sticking with broader compatibility. I have adjusted my documentation for writing Chocolatey scripts to reflect the fact that `Write-Information` should be avoided.

**Comment by pauby** [comment]
As this isn't something we will be implementing, I'm going to go ahead and close this. We can always re-open it again if needed.
