### ISSUE TITLE
Deserializing failures with Package information should not fail the choco run

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#1328]
When deserializing package files file, rarely you may run into this:

~~~
Error deserializing response of type chocolatey.infrastructure.app.domain.PackageFiles:
 '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
~~~

**Comment by ferventcoder** [comment]
Handle serializing issues as well - https://gist.github.com/choco-bot/061d2dde2f278b8c52074753af78d4eb#file-install-txt-L6617

**Comment by Kylotan** [comment]
Was this considered fixed? I had a blue screen during a `choco upgrade all` and when I restarted this process I hit this error. I can see which packages are affected but `choco cache remove` didn't help, nor manually removing what appeared to be corrupt registry files (2K of null characters rather than any XML).

 It would really help if it just mentioned the file it is failing to read!

**Comment by gep13** [comment]
Yes, since the issue is marked as closed, and assigned a milestone, it is believed that this error, as written, has been addressed.  That is not to say that there isn't another code path, that has similar issues.

Can I ask that you raise a new issue, providing as much information as you can regarding the problem you are seeing, including a log file, and ideally, the problematic file.  Thanks!
