### ISSUE TITLE
Add Chocolately signing cert to Trusted Publishers by default

### ISSUE THREAD

**Issue by JW0914** [chocolatey/choco#1508]
While all binaries, except for `bin\packagebuilder.exe`, and both `helpers\*.psm1`'s are signed by the Chocolatey Software, Inc. signing cert, this signing cert is not added to Certificate Manager's Trusted Publishers, and as such is treated as an untrusted signing cert.

* This results with the following upon opening Powershell or Pwsh:
```
Do you want to run software from this untrusted publisher?
File C:\ProgramData\chocolatey\helpers\chocolateyProfile.psm1 is published by CN="Chocolatey Software, Inc.", O="Chocolatey Software,
 Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your system. Only run scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"):
```
* While it's easy enough to simply add the certificate manually via the binaries' properties, this really should be done by the installer script when it's installing chocholately.

This is related to #1214

**Comment by ferventcoder** [comment]
I go back and forth on this, as changing security settings without the user's knowledge could be seen as bad/malicious.

**Comment by ferventcoder** [comment]
> This results with the following upon opening Powershell or Pwsh.

I take it you are getting this every time you open PowerShell? So what happens when your answer is `A`? Does it go away the next time you open it?

**Comment by JW0914** [comment]
I see your point, as that makes sense.  And yes, if you choose A, it will no longer show the error again, if or until the script is updated.

**Comment by ferventcoder** [comment]
I think close for now unless something in this area becomes annoying.

**Comment by unitedpear** [comment]
I want to follow up on this issue (#1508) as I recently encountered a similar prompt when I re-opened my Powershell after a computer restart.

I'm now receiving the following prompts:

```powershell
Do you want to run software from this untrusted publisher?
File C:\ProgramData\chocolatey\helpers\chocolateyProfile.psm1 is published by CN="Chocolatey Software, Inc.",
O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your system. Only run scripts from
trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r

Do you want to run software from this untrusted publisher?
File C:\ProgramData\chocolatey\helpers\functions\Write-FunctionCallLogMessage.ps1 is published by CN="Chocolatey
Software, Inc.", O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your system. Only run
scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r

Do you want to run software from this untrusted publisher?
File C:\ProgramData\chocolatey\helpers\functions\Get-EnvironmentVariable.ps1 is published by CN="Chocolatey Software,
Inc.", O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your system. Only run scripts from
 trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r

Do you want to run software from this untrusted publisher?
File C:\ProgramData\chocolatey\helpers\functions\Get-EnvironmentVariableNames.ps1 is published by CN="Chocolatey
Software, Inc.", O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your system. Only run
scripts from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r

Do you want to run software from this untrusted publisher?
File C:\ProgramData\chocolatey\helpers\functions\Update-SessionEnvironment.ps1 is published by CN="Chocolatey Software,
 Inc.", O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your system. Only run scripts
from trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r

Do you want to run software from this untrusted publisher?
File C:\ProgramData\chocolatey\helpers\ChocolateyTabExpansion.ps1 is published by CN="Chocolatey Software, Inc.",
O="Chocolatey Software, Inc.", L=Topeka, S=Kansas, C=US and is not trusted on your system. Only run scripts from
trusted publishers.
[V] Never run  [D] Do not run  [R] Run once  [A] Always run  [?] Help (default is "D"): r
Loading personal and system profiles took 735071ms.
```

If I'm not mistaken, my choco.exe version was recently upgraded to v0.11.1 (via a `choco upgrade all` command). Is this the expected behaviour any time the base chocolatey package updates? I don't recall having to manually accept this prompt previously.

(Apologies in advance if this is not the correct method/forum to re-address this issue.)

**Comment by vexx32** [comment]
I don't recall if that script was updated recently, but it could well have been. From reading the thread above, it sounds as though it was intentionally left as-is because we didn't want to mess with users' own security settings, which seems reasonable at a glance.

As per the above, I think selecting the `A` option will cause PS to trust the certificate until such time as the scripts are changed again, or the certificate is updated again.

I think this generally only shows with certain security settings enabled, so I've never seen it show up myself.

**Comment by unitedpear** [comment]
@vexx32 Thank you for the response; this makes sense.

> I think this generally only shows with certain security settings enabled, so I've never seen it show up myself.

I tested this out by setting the Powershell execution policy to `RemoteSigned` for the `CurrentUser` scope, while leaving `LocalMachine` as `AllSigned` (`CurrentUser`'s policy will take precedence). This caused the prompt to go away without any user input upon restarting Powershell. Removing the `CurrentUser` execution policy (so that `AllSigned` is once again the execution policy) and restarting Powershell made the prompt re-appear.

You are indeed correct that certain security settings cause this behaviour. I guess it's been so long since I originally encountered this prompt that I forgot I must have accepted it initially at the time.

I suppose selecting `[A] Always Run` is the way to go for those that come across this prompt when the script (or certificate) is updated.
