### ISSUE TITLE
Verification of packages before installing or uninstalling

### ISSUE THREAD

**Issue by lmayorga1980** [chocolatey/choco#151]
First time I installed a chocolatey packages using **choco install** it downloaded the installation media into **C:\ProgramData\Chocolatey\lib**. 

Then I figure out the following:
1. If I uninstall the package from **Windows Program Management** then chocolatey will think the package is already installed just because is on the **lib** folder and it does not run any verification on the **Windows Registry** or something else.
2. If I install a package and then remove the **\lib<package_name>** then **choco install** will still try to install the package even though the package is already present on the **Windows Program Management**

**Comment by ComFreek** [comment]
Re 2:
AFAIK `choco install` always runs `chocolateyInstall.ps1` from the respective package. I've seen some packages which check for the presence of an (up-to-date) installation and don't install anything in this case.

**Comment by ferventcoder** [comment]
1. Turn on autouninstaller before uninstalling.  It will remove it from
windows program management.

2. We are working on enhancing the installer scripts to include the
registry key so we can look it up first.

On Friday, March 6, 2015, Luis Mayorga <notifications@github.com> wrote:

> First time I installed a chocolatey packages using *choco install* it
> downloaded the installation media into *C:\ProgramData\Chocolatey\lib*.
>
> Then I figure out the following:
>
>    1.
>
>    If I uninstall the package from *Windows Program Management* then
>    chocolatey will think the package is already installed just because is on
>    the *lib* folder and it does not run any verification on the *Windows
>    Registry* or something else.
>    2.
>
>    If I install a package and then remove the *\lib<package_name>* then *choco
>    install* will still try to install the package even though the package
>    is already present on the *Windows Program Management*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chocolatey/choco/issues/151>.
>


-- 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by lmayorga1980** [comment]
@ferventcoder I believe puppet has some sort of embedded powershell to check the registry for installed programs. 

It would be nice to check for that before downloading the media into a temporal **lib** folder that it just keeps growing. 

Is there a way to provide a different temporal download folder for installation media?

**Comment by ferventcoder** [comment]
> Is there a way to provide a different temporal download folder for installation media?

Do you mean [cacheLocation](https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/configuration/chocolatey.config#L3)?

**Comment by lmayorga1980** [comment]
Yes

**Comment by marshyski** [comment]
+1 on fix

**Comment by ferventcoder** [comment]
This is a little ways out, we still have to get past bringing all of the powershell scripts into c# powershell functions, then add in a setting for folks to pass to the install function that gives the registry name for us to determine whether or not to install.

**Comment by ferventcoder** [comment]
So you can imagine that this will probably be a slow migration because packages will need to opt in.

**Comment by mrdima** [comment]
I want to give a +1 to part 1 of this issue.
The comment on March 6 about the uninstaller doesn’t help if you remove the package from the gui (programs and features / add/remove programs). Chocolatey keeps thinking the package is still installed and your desired state won’t be fixed by for example Puppet. (unless you can put a force in somewhere but that doesn't feel right)
It would be great if clist -lo  would be a bit more intelligent to see whether a package is installed instead of the lib dir. I thought Rob mentioned something about registry snapshots of the uninstaller part…if those are made at install time and kept somewhere then you could check if one or two of those registry keys still exist For MSI/EXE’s to determine if the package is still installed…those are the most important. For zip type installers I guess you could optionally look at some directory/file still existing (which you could optionally use for MSI/EXE as well actually…something like that is even in SCCM to determine whether an application (not package) is installed, so not even uncommon I guess).
