### ISSUE TITLE
choco powershell install fails if non-existing directories are in %LIB%

### ISSUE THREAD

**Issue by Trolldemorted** [chocolatey/choco#1551]
### What You Are Seeing?
Title says it all

### What is Expected?
It works

### How Did You Get This To Happen? (Steps to Reproduce)
- add a dir that does not exist to %LIB%
- try to install choco

### Output Log
https://pastebin.com/4pAs0ymt

**Comment by ferventcoder** [comment]
What is %LIB%?

**Comment by Trolldemorted** [comment]
Yup, I am using the normal powershell of W10. After removing the stale paths from %LIB% the install worked.

[%LIB% is an environment variable where microsoft's linkers look for .lib files](https://docs.microsoft.com/en-us/cpp/build/reference/dot-lib-files-as-linker-input):
> If no path is specified, LINK looks first in the directory that LINK is running from, and then in any directories specified in the LIB environment variable

**Comment by ferventcoder** [comment]
@Trolldemorted I'm not sure why this would have caused PowerShell to throw errors, but it sounds like it might have failed with other calls to PowerShell that would access environment variables. I believe we can add something to our troubleshooting docs, but as this is with PowerShell and not with Chocolatey, I'm not sure what else could be done. 

We could temporarily redefine the LIB environment variable, but then what happens when a different one has issues?

**Comment by Trolldemorted** [comment]
Are you sure there is no way to interact with environment variables in powershell that allows using invalid paths?

**Comment by ferventcoder** [comment]
@Trolldemorted to be honest, we don't even look at that, it would be something in PowerShell itself that is throwing the error. If you know how to do what you are asking, we are open to getting it added to the installation script and will accept pull requests to do so. The script in reference is actually over at https://github.com/chocolatey/chocolatey.org - thanks in advance!

**Comment by gep13** [comment]
Due to lack of response on this issue, I am going to go ahead and close it out.  If you feel that there is still work to be done here, please feel free to comment again, and we can revisit.
