### ISSUE TITLE
Change default behavior of `choco list` to be local only

### ISSUE THREAD

**Issue by findel** [chocolatey/choco#158]
The current default behaviour of `choco list` (or `clist`) is to list ALL of the packages available on chocolatey (currently 2596 in total). This is a little slow, and not really helpful as a default. 

Couldn't the default behavior be to display "local only" packages, displaying only packages that are installed locally, as when you do `choco list --localonly`?

Then require switches to get data from the repositories, rather than the other way around?

# Implementation Notes

When this work is undertaken, the deprecation notices that were add in this PR will need to be reviewed/removed:

https://github.com/chocolatey/choco/pull/2626

**Comment by ferventcoder** [comment]
I love the idea of this - I want to get an idea of what it may require from other tools as this would be a breaking change.

**Comment by alexchandel** [comment]
`choco list` should absolutely list only locally installed packages by default. We already have `choco search` with no arguments to list ALL packages.

**Comment by ferventcoder** [comment]
Search and list are aliases

**Comment by darrelmiller** [comment]
:+1:

**Comment by christianrondeau** [comment]
Agreed on `list` being `--localonly` by default, and maybe `search` could not be an alias anymore? I also thought that `search` was server-based, and `list` was not. It may be interesting to run a quick survey if you're not sure.

**Comment by alexchandel** [comment]
@christianrondeau I would instinctively assume `list` was local only, and only listed packages installed by default.

@ferventcoder Can this please happen in 0.9.9.7? It's intuitive (`list` gives your packages, `search` without any filter gives all packages), it parallels the behavior of other package managers, and it has broad backing. It's a breaking change, but it affects users who are exploring chocolatey packages, not scripts (compare with `choco install`), so its impact is limited.

**Comment by ferventcoder** [comment]
@alexchandel it's intuitive for you but it is a breaking change, so that's why the milestone is 1.0.0. Folks need time to prepare for the break.

**Comment by ferventcoder** [comment]
@alexchandel and it is used by applications that are building on top of chocolatey.

**Comment by alexchandel** [comment]
@ferventcoder Is there any application known to use `choco list` instead of `choco search`, besides possibly ChocolateyGUI?

**Comment by ferventcoder** [comment]
puppet choco provider / chef cookbook / boxstarter

**Comment by alexchandel** [comment]
@ferventcoder So from what I saw, the three packages you mentioned all use `choco list` for local searches already (I should've specified that!) and won't be affected by this change. So it should be reasonably safe to implement.

**Comment by RichiCoder1** [comment]
@gep13 Does this break us with new provider? I know the old one used OData directly.

**Comment by ferventcoder** [comment]
@RichiCoder1 maybe? It is going to follow a semver break boundary, likely v1.

**Comment by RichiCoder1** [comment]
If that's the case, then we'll probably have fixed the gui to use chocolib by then and it'll be a non-issue.

**Comment by gep13** [comment]
@RichiCoder1 yes, we are likely to run into some issues with this. But as you say, switching to the use of the lib will ultimately be the correct path forward.

**Comment by alexchandel** [comment]
@ferventcoder Can this please happen? I ended up with a corrupted XML settings files after I had to Control+C to stop an accidental `choco list` from wasting 5 minutes.

**Comment by ferventcoder** [comment]
@alexchandel Absolutely. Note that we've already set a milestone and version for this.

**Comment by vexx32** [comment]
A milestone is great, but do we have a timeline on where it falls along that path, or a release timeline up to 1.0 somewhere?

**Comment by ferventcoder** [comment]
@vexx32 understand the timings are slower than you might like, but it's something that must be moved and transitioned on slowly - otherwise we break many things (and it's likely we would anyway because sometimes folks don't read, but at least they've had the potential to do so).

**Comment by vexx32** [comment]
Merely commenting on the timeline because most products have a fairly regular breaking changes pattern that is well fleshed out, and also because a target without a set date tends to get forgotten very quickly.

As a handful of the folks in the PowerShell slack/discord mentioned, it might be worth implementing it as a optional configurable feature first; that way it won't break anything in its default configuration. If we also are able to track in some unobtrusive method which features like this are being used and on what % of machines, we can then look at defining more concrete timeline of swapping which is default, and eventually deprecating the lesser-used option if it falls out of use.

**Comment by markekraus** [comment]
How about add a `choco listlocal` and `choco listremote` and then add a new option to `choco list` to be like `choco list --default-source=local`. Then when you release a major version with other breaking changes you can alter the default behavior of `choco list`. This will allow you to implement now and break later.

**Comment by vexx32** [comment]
Yeah that, thanks @markekraus 😄

**Comment by ExE-Boss** [comment]
You could use a `use‑beta‑cli` config option, [like what pnpm does](https://pnpm.js.org/en/npmrc#use-beta-cli).

**Comment by ethanbergstrom** [comment]
Hey all - chiming in as the de-facto maintainer of ChocolateyGet and the underlying Crescendo module it depends on. Totally in favor of this change, but wanted to clarify something...

On https://docs.chocolatey.org/en-us/choco/commands/list#examples, it says: `choco list --local-only (DEPRECATED: will be default for list in v2.0.0)`. 

Does that mean the `--local-only` parameter will just be ignored? Or does that mean if you were to still pass `--local-only` post-v2 that it would cause unintended errors/results?

If it's just accepted and ignored, that should work just fine. However, if the thought is `--local-only` becomes just another string passed to `list` that it then tries to interpret (ex: it gets treated as a package name filter), that could be pretty problematic for script maintainers trying to support large ranges of choco version.

**Comment by gep13** [comment]
@ethanbergstrom :wave: thanks for reaching out!

By default, Chocolatey doesn't do strict parsing of option passed into the command line.  This is by-design, and allows for unparsed arguments to be ignored and used in other ways.  When we remove the `--local-only` option, it will become an unparsed argument, which as it is currently written, would mean that it would become the search term for the list command.

To explain this via an example, if you did the command:

```
choco list bob
```

`bob` would be the search term used to look for packages.

If you did the command

```
choco list bob --local-only
```

then the search term would be `bob --local-only` which as you hinted at, would have unintended consequences, since it wouldn't return any search results.

We are getting ready to undertake the work associated with this issue, so let me discuss this further with the team, and make a decision about how we want to progress with this.

**Comment by ethanbergstrom** [comment]
@gep13 - yeah that sounds scary for me :)

If `--local-only` could be kept as a parsed argument but not hooked up to any behavior / ignored, it would be a lot less impactful to script maintainers and would give folks a smoother migration path.

Thanks for the consideration!

**Comment by gep13** [comment]
> @ethanbergstrom said...
If --local-only could be kept as a parsed argument but not hooked up to any behavior / ignored,

There are complications here, mainly due to the fact that the presence of the option in the C# code is what generates the documentation on the website.  So we are likely going to have to do more in this area if we choose to ignore the option.

Not impossible, just something that we need to consider.

**Comment by TheCakeIsNaOH** [comment]
> There are complications here, mainly due to the fact that the presence of the option in the C# code is what generates the documentation on the website.

It may make sense to keep `--local-only` on the docs website, with the description noting that it is only applicable to 0.x and 1.x versions.

**Comment by agabrys** [comment]
What do you think of deprecating the parameter in steps?

#### First Version (Current State)

The `--local-only` parameter works normally (returns only local packages).

```
> choco list --local-only
// packages list
```

#### Next Version (Deprecation)

Make `choco list --local-only` as the default behaviour and mark the `--local-only` parameter as deprecated (when it is used, `choco` prints a warning message that the paremeter is deprecated and should be removed)

```
> choco list --local-only
The --local-only parameter is ignored, remove it please // warning message, probably to system.err,
                                                        // so system.out contains only the packages list
// packages list
```

Would be good to keep that behaviour for around 3 months, so developers have time to update their scritps (remove the parameter).

#### Last Version (Remove Deprecation)

The `--local-only` parameter is no longer interpreted (use to print a warnign message), so it is threated as a filter query.

```
> choco list --local-only // --local-only is interpreted as a filter parameter
// packages list
```

**Comment by ethanbergstrom** [comment]
Any update on the intended design approach for this change?

I've got ethanbergstrom/Foil#9 staged and ready to go, assuming we're able to keep `--local-only` as a parsed argument disconnected from any behavior. Once that's published, I need a make a few changes downstream to ChocolateyGet as well, in order to consume it.

**Comment by AdmiringWorm** [comment]
One correction as well, my previous comment will only be available for v2 of Chocolatey CLI, and local only will be removed entirely and not even ignored in v3 of Chocolatey CLI.

**Comment by vexx32** [comment]
After some internal discussion with the team, we've decided to go ahead with ignoring `--local-only` and related arguments (`-li`, etc) for `choco list`. There will be a warning outputted to the log file only, but not emitted to output / the console.

**Comment by ethanbergstrom** [comment]
It looks like the Chocolatey team went back on the understanding we had in this thread, where `--local-only` would be parsed but ignored.

I tried to create a seamless experience for the users of my scripts to maintain a level of passivity, but that all seems to have been for naught. 

Very disappointing for a piece of software designed to make the lives of Operations folks easier.

**Comment by pauby** [comment]
If you are using `--limit-output` or `-r` (which is designed for automations and computer readable output) nothing changes. Automations and scripts will continue to run with only a warning added to the logs.

If you are a user at the desktop running `choco list --local-only` then you'll get an error.

See the [upgrade guide](https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6#the-list-command-now-lists-local-packages-only-and-the-local-only-and-lo-options-have-been-removed)
