### ISSUE TITLE
outdated - Use exit codes to determine update status

### ISSUE THREAD

**Issue by proudcanadianeh** [chocolatey/choco#1602]
Would absolutely love different exit codes for choco outdated for if it does or does not find packages that need to be updated. 

Would make it very easy to script a check that way.

**Comment by bcurran3** [comment]
@proudcanadianeh - consider giving some examples of your preferred output for the Chocolatey Team to consider. Help steer them towards what you want. :)

**Comment by proudcanadianeh** [comment]
For my purposes, have an exit code of 0 if everything is up to date, 5 if stuff is out of date, 10 if there is an error checking for updates.

**Comment by cs96and** [comment]
I would like some exit status from `choco outdated` too.  I have written a PyQt system tray app that runs "choco outdated" one per day and notifies the user if there are any updates available...
https://bitbucket.org/cs96and/choco-toast/src

The problem I have is that the python script cannot tell if an error occurs (e.g. if my internet connection is down), and reports all the error messages as available updates.  This is exacerbated by two additional problems...

1. All errors are reported to stdout instead of stderr, even if `--fail-on-stderr` option is given.
2. Each error message is followed by the package details, as if that packe is actually outdated.  E.g....

```
choco outdated --limit-output --nocolor --ignore-pinned --no-progress --fail-on-stderr -s https://127.0.0.1/doesnt/exist
[NuGet] An error occurred while loading packages from 'https://127.0.0.1/doesnt/exist': Unable to connect to the remote server
7zip|18.5.0.20180730|18.5.0.20180730|false
[NuGet] An error occurred while loading packages from 'https://127.0.0.1/doesnt/exist': Unable to connect to the remote server
7zip.install|18.5.0.20180730|18.5.0.20180730|false
```

**Comment by ferventcoder** [comment]
@cs96and I think you are missing an additional switch `--ignore-unfound`.

**Comment by ferventcoder** [comment]
@cs96and Some of that could be that `[NuGet]` portions of the log still write to stdout instead of stderr and possibly don't affect the fail on stderr option. Probably best for you to file new issues for those two things so they don't get lost. Thanks in advance!

**Comment by ferventcoder** [comment]
@proudcanadianeh this is a great idea! I think we'll want to approach this for next release. Error would be exit code 1 though.

**Comment by cs96and** [comment]
Using `--ignore-unfound` gets rid of problem 2.  I'll file a separate bug report about problem 1.

**Comment by ferventcoder** [comment]
This will be released with 0.10.12. Thanks for the patience on this one.

**Comment by xtimon** [comment]
https://docs.microsoft.com/en-us/windows/desktop/debug/system-error-codes--0-499-

**Comment by xtimon** [comment]
ERROR_FILE_NOT_FOUND

    2 (0x2)

    The system cannot find the file specified.

**Comment by xtimon** [comment]
How to avoid the invalid exit code?

**Comment by xtimon** [comment]
choco feature disable --name="'useEnhancedExitCodes'"
