### ISSUE TITLE
Only install listed package as dependency

### ISSUE THREAD

**Issue by franklinyu** [chocolatey/choco#1645]
Currently `choco.exe` will not install latest version of `foo` if it has not yet pass all the validation, testing, and approval. However, when resolving dependencies, unlisted packages are considered fine.

Example: Currently `rclone.install` has 1.39 listed and 1.42 unlisted. `rclone` has 1.42 listed which depends on `rclone.install` 1.42. `cinst rclone.install` installs 1.39, while `cinst rclone` installs 1.42.

An option like `listedOnlyDependency` would be very good if this is consider a breaking change.

**Comment by ferventcoder** [comment]
This is by design - if a package is unlisted but is a dependency, then that package should not be broken.

**Comment by ferventcoder** [comment]
If we'll consider a different option for what happens if that package is under moderation still, the package that was listed should not have been approved until all dependencies were approved as well.

That scenario that you are seeing is a bug with Chocolatey.org, so best to write up an issue with what I stated here at https://github.com/chocolatey/chocolatey.org - thanks!

**Comment by ferventcoder** [comment]
@franklinyu looks like this is already an issue - please watch at https://github.com/chocolatey/chocolatey.org/issues/576
