### ISSUE TITLE
keystrokes 

### ISSUE THREAD

**Issue by necrose99** [chocolatey/choco#1669]
https://blogs.technet.microsoft.com/heyscriptingguy/2011/01/10/provide-input-to-applications-with-powershell/

else a chco helper to record keys or mouse clicks  , 
ie Everquest 2 or Eq1 installer had often ALT N for Next Accept etc. 

any rate can record app install ie the clicks , to add to choco-install-ps1 to replay them as the app launches.  next/yes yes yes done..  ie just record the application install ... mouse and keys , then sugest a powershell wrapper to add into the nuget pkg.. 

https://stackoverflow.com/questions/17849522/how-to-perform-keystroke-inside-powershell

**Comment by necrose99** [comment]
any rate ALT N next or other _N_ or other keystrokes that move along installer menu dialogs could be pushed.

**Comment by pauby** [comment]
@necrose99 Have you looked at AutoHotKey? That does all of this and more.

**Comment by ferventcoder** [comment]
Thank you @necrose99, but I don't believe this is a direction we are looking to go at this time, as there are other tools out there that perform this (AutoHotKey or AHK as @pauby mentioned). Plus it's not deterministic in that it can only be used interactively (won't work with Windows services running choco due to Session 0 isolation - AHK suffers from the same issue), it might be language dependent, and like AHK it would be fragile at best.

**Comment by necrose99** [comment]
any rate it was for apps , but i take it one can use granit etc. to make a wrapping script.. 
but i'll take a look at AHK ... 

i figured for simplistic menus , one could add a few keystrokes in for something easy ish. 
ie next next yes yes ok , thier is powershell / cmd to do this but not as clean. 
but so noted.. t i'll take a look at AHK ...
