### ISSUE TITLE
Rebooted without warning

### ISSUE THREAD

**Issue by Y-Less** [chocolatey/choco#1671]
Ensure you have read over Submitting Issues -
https://github.com/chocolatey/choco#submitting-issues

Please check to see if your issue already exists with a quick search of the issues. Start with one relevant term and then add if you get too many results.

NOTE: Keep in mind we have an etiquette regarding communication that we expect folks to observe when they are looking for support in the Chocolatey community. https://github.com/chocolatey/choco/blob/master/README.md#etiquette-regarding-communication
-->

### What You Are Seeing?

I was installing a package (node) while doing some other work (a calculation for which had been running for several hours).  Suddenly my machine rebooted without warning.

### What is Expected?

Not reboot without warning!

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
PLACE LOG CONTENT HERE - WE NEED _ALL_ DETAILED OUTPUT BASED ON THE ABOVE TO BE ABLE TO PROVIDE SUPPORT (YOU WILL FIND THAT IN THE $env:ChocolateyInstall\logs\chocolatey.log between the `=====`)
~~~

</p>

</details>

**Comment by gep13** [comment]
@Y-Less thank you for taking the time to raise this issue, and I am sorry to hear that you have had problems.

The issue is actually outwith the confines of this repository.  This is actually being discussed, along with other issues regarding the changes to the Node installer here:

https://github.com/nodejs/node/issues/23838

There is also a Pull Request to add additional warnings about what will happen during the installation here:

https://github.com/nodejs/node/pull/23987

**Comment by Y-Less** [comment]
This should be restricted at the package manager level, such that nothing installed via Chocolatey even has the ability to disrupt people in this way.  It isn't an issue with just one repo, even though that is the one I experienced it on.
