### ISSUE TITLE
Can't search for package but install it (freecad)

### ISSUE THREAD

**Issue by matthiaslischka** [chocolatey/choco#1681]
### What You Are Seeing?
I can't search for a package (freecad) event though it should be there. I can even install it but not search for it.

### What is Expected?
It should list the package

### How Did You Get This To Happen? (Steps to Reproduce)

> C:\WINDOWS\system32>choco search freecad
> Chocolatey v0.10.11
> **0 packages found.**
> 
> C:\WINDOWS\system32>choco install freecad
> Chocolatey v0.10.11
> **Installing the following packages:**
> **freecad**
> By installing you accept licenses for the packages.

BR Matthias

**Comment by matthiaslischka** [comment]
It is working now!

In between I got

> C:\WINDOWS\system32>choco search freecad
> Chocolatey v0.10.11
> The remote server returned an error: (503) Server Unavailable.

However, now it works as expected again.

BR Matthias

**Comment by bcurran3** [comment]
The Chocolatey website cache server has problems now and then. It's a known issue. We just need to sit back and wait for it to be fixed in time.

You can monitor when the site has (known) problems at:
https://status.chocolatey.org/

There are also announcements on Twitter and Google Groups when there is a problem or maintenance.
