### ISSUE TITLE
-OutputDirectory is not work

### ISSUE THREAD

**Issue by Claud** [chocolatey/choco#173]
Hello. All my scripts for building packages is broken.

Why you change build commands?!!!

https://github.com/Claud/chocolatey-packages/blob/master/winscp/src/1-build-package.bat
https://github.com/Claud/chocolatey-packages/blob/master/winscp/src/3-push-package.bat

**Comment by gep13** [comment]
Hello Claud,

Sorry to hear that you are having issues with the new release of Chocolatey.  To be clear though, the `cpack` command never had a `-OutputDirectory` switch, as you can see documented here:

https://github.com/chocolatey/chocolatey/wiki/CommandsPack

The reason that this worked for you is that cpack was simply a light wrapper around the `nuget pack` command, which does have an `-OutputDirectory` switch, as documented here:

https://docs.nuget.org/consume/command-line-reference#update-command-options

I can't speak to whether it was intended to provide this functionality in Chocolatey < 0.9.8.33.  Looking at the source code:

https://github.com/chocolatey/chocolatey/blob/master/src/functions/Chocolatey-Pack.ps1

It seems clear that the intention was only for the packageName, i.e. the nuspec file, to be passed through, not the additional arguments for the underlying `nuget pack` command.

Now that Chocolatey > 0.9.9.0 uses the Nuget Core Dll, rather than direct calls to nuget.exe, your additional parameters are not being respected.  However, this is very much an edge case of usage, so I am not sure what can be done.

To correct your scripts, you would need to simply use `nuget pack` rather than `cpack`, and it should work as it used to.

**Comment by ferventcoder** [comment]
Okay, originally this was not an issue because it was using behavior we never implemented. However #598 was just filed to ask for this behavior, so I will leave that open.
