### ISSUE TITLE
install any app using choco it prmpts to how do i open the file

### ISSUE THREAD

**Issue by devopslearningteja** [chocolatey/choco#1805]
![chocoerror](https://user-images.githubusercontent.com/43385451/56432686-f17f5000-62eb-11e9-9ac3-a06f7dc936b8.png)

**Comment by gep13** [comment]
@devopslearningteja thank you for reaching out, but in order to best help you, we are going to need you to provide more details.  Can you provide a full set of steps on how we can reproduce this problem?  What steps did you take to install chocolatey?  What version are you using?  What Operating System are you using?  What version of PowerShell are you using? 

The more information that you can provide, the more likely it is that assistance can be provided.

**Comment by bcurran3** [comment]
Reboot.
Re-install Chocolatey if the problem persists.

Some association has been made with choco that isn't correct/normal/supposed to be that way.

Try also typing choco.exe instead of just choco and I'm guessing things WILL work for you currently.

**Comment by ferventcoder** [comment]
You have a file in your System32 directory you need to go find and remove. Copy and run this command EXACTLY `where.exe choco` (you need the .exe for it to work appropriately).

**Comment by ferventcoder** [comment]
HTH
