### ISSUE TITLE
fail to install python2 2.7.16

### ISSUE THREAD

**Issue by iliveforfun** [chocolatey/choco#1842]
when installing choco, it tolds me that python2 failed installing. so i choose to reinstall it. but it still failed.
**the log is as below:**
`2019-06-04 18:14:31,346 12156 [DEBUG] - Attempting to delete file "C:\Users\shinsuke\AppData\Local\NuGet\Cache\python2.2.7.16.nupkg".
2019-06-04 18:14:33,524 12156 [ERROR] - 2.7.16 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more 
 assistance.
2019-06-04 18:14:33,532 12156 [WARN ] - 
Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2019-06-04 18:14:33,534 12156 [INFO ] - 
2019-06-04 18:14:33,536 12156 [ERROR] - Failures
2019-06-04 18:14:33,537 12156 [ERROR] -  - 2.7.16 - 2.7.16 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more 
 assistance.
2019-06-04 18:14:33,540 12156 [DEBUG] - Sending message 'PostRunMessage' out if there are subscribers...
2019-06-04 18:14:33,561 12156 [DEBUG] - Exiting with 1`

**the wrong information in powershell is as below:**
`Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - 2.7.16 - 2.7.16 not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify --pre,
 the package may not be found.
Please see https://chocolatey.org/docs/troubleshooting for more assistance.`

**Comment by ferventcoder** [comment]
I am looking at a very small portion of the log. We ask for the full log for a reason, because it illustrates things that most folks miss and we can assist with. 

However, from this small portion of the log, I can tell you've typed something to the effect of `choco install python2 2.7.16` which equates to install python2 and a package named "2.7.16" (`choco install pkg1 [pkg2 pkgN]`). I think you meant to type `choco install python2 --version 2.7.16`.

So it appears it installed python2 correctly and didn't install a non-existent package correctly. 

I'm going to close this as invalid. If you see this as otherwise, please go ahead and reply and we can sort out with a full log. Thanks!
