### ISSUE TITLE
When selecting not to install an update, chocolatey asks for a rollback

### ISSUE THREAD

**Issue by christianrondeau** [chocolatey/choco#188]
If I decide not to continue with the uninstall by refusing to run the script, I'm expecting _not_ to receive a request to rollback. Here is an example:

``` bash
Do you want to run the script?
 NOTE: If you choose not to run the script, the installation will
 fail.
 Skip is an advanced option and most likely will never be wanted.

 1) yes
 2) no [Default - Press Enter]
 3) skip
no
filezilla upgrade not successful.
User cancelled powershell portion of installation for 'C:\ProgramData\chocolatey\lib\filezilla\tools\chocolateyInstall.ps1'.
 Use skip to install without run.
 Unsuccessful operation for filezilla.
  Do you want to rollback to previous version (package files only)?
 1) yes [Default - Press Enter]
 2) no
no
```

Note that the rollback message itself could also be improved :)

For more details: https://groups.google.com/forum/#!topic/chocolatey/UVncL7PxXRg

(Moved from https://github.com/chocolatey/chocolatey/issues/696)

**Comment by rismoney** [comment]
if you control-c at the menu, it has alredy downloaded the spec, and createdf the dir in /lib so it thinks that the package is installed on a subsequent rerun.

**Comment by christianrondeau** [comment]
In the example outlined in the original post, there was no <kbd>ctrl</kbd> + <kbd>c</kbd> but I guess it could lead to the same result. A potential "simple" solution (just throwing ideas) would be to flag a package as "not successfully installed" until it has ben installed completely, so that after the operation has completed unsuccessfully, the package is simply removed. *If* what you just said is true (I don't actually know :))

**Comment by DarwinJS** [comment]
As an implementation detail I would suggest having flag files in the package folder rather than using the folder as a marker.  This would allow chocolatey to sense that there have been failed installs and clean them up or even show alerts in some type of audit mode or in "choco list -lo"

Options for install status could be "user aborted", "incomplete", "error".

Could start the install with "installstatus.incomplete" and at the end change to "installstatus.installed"  If other handled conditions arise, leave off with that status "installstatus.userabort".  "installstatus.error" - the file could contain the error text.

Just ideas - I'm sure you guys will figure out a great way to handle it.
D.

**Comment by ferventcoder** [comment]
A user cancelled script will auto rollback - https://github.com/chocolatey/choco/issues/985

**Comment by ferventcoder** [comment]
Forgot this was here when I put in the work for the 0.10.2 release
