### ISSUE TITLE
Choco package install permission issue

### ISSUE THREAD

**Issue by thelastofreed** [chocolatey/choco#1942]
### What You Are Seeing?

This is actually a continuation of issue #1897.  It turns out we were both wrong in regards to what was throwing the error that was causing the chocolatey package to fail installation, as the reg file in the package is being imported successfully.  To refresh your memory, this is the contents of the chocolatey install script:

```

$ErrorActionPreference = 'stop';
$toolsDir   = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
$fileLocation = Join-Path $toolsDir 'anyconnect-win-4.6.01098-nam-predeploy-k9.msi'

$packageArgs = @{
  packageName   = $env:ChocolateyPackageName
  unzipLocation = $toolsDir
  fileType      = 'MSI'
  file         = $fileLocation

  softwareName  = 'vpnnam*'

  checksum      = 'C53558B1AEB41C7F8E33D67EBE07D33FC326B0D2F567B452317443B3DE3A94A3'
  checksumType  = 'sha256'

  silentArgs    = "/qn /norestart /l*v `"$($env:TEMP)\$($packageName).$($env:chocolateyPackageVersion).MsiInstall.log`""
  validExitCodes= @(0, 3010, 1641)
}
choco install vpnpredeploy -y -s $env:USERPROFILE\Desktop
Install-ChocolateyInstallPackage @packageArgs
reg import "$toolsDir\vpn-omnichan.reg"
Copy-item "$toolsDir\USAN_logo-2.png" "C:\Windows\" -force
Copy-item "$toolsDir\configuration.xml" "C:\ProgramData\Cisco\Cisco AnyConnect Secure Mobility Client\Network Access Manager\newConfigFiles\" -force
Write-host "A restart is required in order to complete the software installation."
```

The part of the script that is generating the error when chocolatey is installing the package is the "copy-item" operation that is right after the "reg import" operation:

```
Copy-item "$toolsDir\USAN_logo-2.png" "C:\Windows\" -force
```

I assume this is the case because of the elevated permissions that are needed in order to copy files to the windows folder.  However, I do not see why chocolatey would encounter a problem when the command to install the package was run from an elevated command prompt.  I would assume that chocolatey is able to run the powershell commands within the package under the same, elevated context that the package installation command was run from, but this does not appear to be the case, as neither of the files which should have been copied in the two "Copy-file" operations are in the destination folders they should be in.  Furthermore, when performing the command manually by launching an elevated powershell console and using copy file to copy the files from the extracted package contents on the local machine to their destinations, it does so successfully.  Why is chocolatey running into this (what I assume to be) permissions issue?
 
### What is Expected?

The copy-file operations should successfully be copied to their destination folders when the package installation command is run from an elevated shell.

### How Did You Get This To Happen? (Steps to Reproduce)
In the chocolatey installation script, Try to copy a file from chocolatey's $toolsdir to the local machine's "C:\windows" folder, create the package, and try to install the package with chocolatey.
### Output Log

Please see issue #1897, as it is still the same issue and will have the same logs.

**Comment by ferventcoder** [comment]
Howdy @thelastofreed - unfortunately, like I mentioned previously, it's still likely something going on in the packaging itself and not an issue with Chocolatey. You might have a file locked, being held by the AV scanner, not yet created, or something else. It could also still be reg import, because even when successful, it will return a non-zero exit code. That's why I pointed to it as a possible issue.

While unlikely, there is also a feature setting in choco if you have it set, it will fail the package if something like this returns non-zero. We've deprecated that setting, so please make sure it is not turned on for you (`choco feature disable -n scriptsCheckLastExitCode`). 

Notes:
* I noticed you added a choco install call to your script - it's a complete anti-pattern to do so. Remove `choco install vpnpredeploy -y -s $env:USERPROFILE\Desktop` completely from your script. Take a dependency on vpnpredeploy in the nuspec instead.
* Ensure the file USAN_logo-2.png is being packaged inside the package itself and is not create as part of the rest of the script running
* reg import / query will always return a non-zero exit code, even when successful. This is why I pointed to it as a possible issue for your package
* One of the scripts/installer you are calling before you call Copy-Item could be restricting permissions/token, even if it is unlikely. However that is still a packaging issue.

Some things to try:

* comment out the lines starting at reg import to the end of the file. Uncomment one at a time, build the package, and run it. When it fails again, then you will know which one is causing the error. 
* Change from using reg import to using built-in PowerShell methods instead.

Good luck. As this is still not likely an issue with Chocolatey, I'm going to go ahead and close it. If you do get to a point where you've built a package that just attempts to copy something into C:\Windows and it errors, then I can reopen this issue on that regard. However we'd need minimal repro for the issue, and this package has a lot of things it is doing, at any point there could be something causing the issue.
