### ISSUE TITLE
Python is not added to Path

### ISSUE THREAD

**Issue by aminya** [chocolatey/choco#2043]
I tried `choco install python`, however, my Windows path is not updated.

**Comment by teknowledgist** [comment]
First, an issue with a package is more appropriately reported in the package's maintainer's repository.  For the python package, [that is here](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues).

Second, the package is using the proper commands to add the path according to [the Python documentation](https://docs.python.org/3/using/windows.html?highlight=prependpath#installing-without-ui).  If it isn't working for you, it could be your machine or it could be a problem with the Python installer and is more appropriately handled by [the Python Community](https://www.python.org/community/forums/), not Chocolatey.

**Comment by Zericardos** [comment]
I just have to restart my PC to update path

**Comment by codespearhead** [comment]
Since this is the top Google result for "Chocolatey not adding Python to PATH", I decided to comment it here:

Windows 10 introduced these "app execution aliases" for "python.exe" and "python3.exe". They're turned on by default [1][2][3], so whenever you type those commands, Windows reroutes them to a message like "Python was not found; run without arguments to install from the Microsoft Store".

To fix it, just head over to "Settings > Apps > Advanced app settings > App execution aliases",  disable those two aliases, restart you machine, then reinstall Python with "choco install python --force". [4]

[1] https://answers.microsoft.com/en-us/windows/forum/all/are-pythonexe-and-python3exe-present-under-app/bac9429e-3d7d-44ba-a2a8-90b2522a1ce8
[2] https://github.com/chocolatey-community/chocolatey-packages/issues/1625
[3] https://github.com/chocolatey-community/chocolatey-packages/issues/1625#issuecomment-802357404
[4] https://github.com/chocolatey-community/chocolatey-packages/issues/1625#issuecomment-803679898
