### ISSUE TITLE
upgrade: Add a switch to disable pin when upgrade

### ISSUE THREAD

**Issue by CookieHCl** [chocolatey/choco#2050]
## Motivation

I've pinned `powershell-core` because you mess up if you upgrade PowerShell Core in PowerShell Core.  
So when I have to upgrade PowerShell Core, I have to remove pin and upgrade and add pin again.
Specifically, I follow this procedure:

1. `choco upgrade all` in PowerShell Core
2. Checks Powershell Core has an upgrade (with `this package is pinned` warning message)
3. Go to safer terminal (such as PowerShell 5.1)
4. `choco pin remove -n=powershell-core` in Powershell
5. `choco upgrade powershell-core` in Powershell
6. `choco pin add -n=powershell-core` in Powershell

The point is someone uses pin for delay upgrades, not to block upgrades forever.

## Solution

Add a switch `--disable-pin` to upgrade.
When this switch is enabled, pinned packages will be upgraded.
`choco upgrade powershell-core --disable-pin` has same effect with the above procedure 4-6.

## Other suggestions

Switch name could be

- `--ignore-pin`
- `--exclude-pin`
- `--disable-pin-once`

**Comment by ferventcoder** [comment]
I think this may already be an issue? Or at least something related like install with pin.

**Comment by FarrelBuch** [comment]
Hear, Hear!
I could not agree more. 
I asked this exact question on [StackExchange Super User](https://superuser.com/q/1582019/31235). 

At the least, it would be nice if the documentation for pinning explicitly stated that there is no way to temporarily bypass the pin. One can only manually remove the pin, upgrade and repin. 

Notwithstanding my asking for more, Chocolatey is really good. Thank you.

**Comment by nkrepo** [comment]
> 
> 
> I think this may already be an issue? Or at least something related like install with pin.

@ferventcoder is there any progress with that feature ?

**Comment by nascentt** [comment]
The [Chocolatey docs specifically recommend](https://docs.chocolatey.org/en-us/features/package-synchronization/automatic-sync#automatic-updating-software) using pin as a solution for auto-updating apps like Firefox and Chrome, as apparently [auto synching doesn't work for package updates](https://docs.chocolatey.org/en-us/features/package-synchronization/automatic-sync#more-details-on-external-upgrades).  Yet that leaves no way to manually roll out packages updates to the hosts that don't keep those auto-updating applications constantly open.

I don't understand why pinning doesn't just only prevent "choco upgrade all", or hide the package in "choco outdated".  Preventing the package from updating at all is a poor solution especially when there's no administrative way to just issue a package upgrade without fiddling around with toggling the pin off and on again.

**Comment by TheCakeIsNaOH** [comment]
> no administrative way to just issue a package upgrade without fiddling around with toggling the pin off and on again.

@nascentt how about using `upgradeAllExceptions` instead of pins? See `choco config -h` for more info on the setting.

**Comment by nascentt** [comment]
> > no administrative way to just issue a package upgrade without fiddling around with toggling the pin off and on again.
> 
> @nascentt how about using `upgradeAllExceptions` instead of pins? See `choco config -h` for more info on the setting.

strange, I don't see upgradeAllExceptions mentioned at all in `choco config -h`.  Additionally, I don't see it documented anywhere, only getting 7 results in google.
Playing around with both methods, I'm unsure of the main use case for one over the other. both require chocolatey admin knowledge to bypassed, and both can be bypassed, neither prevent apps showing up in `choco outdated` by default, although there is a switch to ignore pinned in choco outdated it's not default. But upgradeAllExceptions is good because it completely hides packages by default, but that's only for upgrade and not outdated so can still confuse users.

I guess neither solution really fixes the underlying issue that choco sync doesn't work for version changes, which should really be fixed.

I do still believe choco upgrade should have a switch to ignore pins the same way choco outdated does though.  For both preventing hacky workaround like disable;upgrade;enable, but also consistency.

regarding the name, as choco upgrade has -ignore-pinned I feel the name of the switch on choco upgrade should be the same

`choco ugrade --ignore-pinned`

**Comment by TheCakeIsNaOH** [comment]
Whoops, sorry that should be `choco config -l`

**Comment by gep13** [comment]
In order to be consistent with an existing option on the `outdated` command, the decision was taken to go with `--ignore-pinned` as the option for this feature.
