### ISSUE TITLE
Choco uninstall <pkg_name> -y still prompt the Yes/No question

### ISSUE THREAD

**Issue by nissim-attr** [chocolatey/choco#2070]
Hi,
I'm trying to uninstall pkg also from Programs and Features
By using both Cli and Chocolatey.lib version 0.10.15 with the command :
"Choco uninstall <pkg_name> -y"
But it still prompt the Yes/No question regards to AutoUninstaller.
And it keeps waiting for 30 seconds untill timeout.

In Chocolatey.lib I cofigured the AutoUninstaller=true as well
Also tried to pass -y in the InstallArgumets
but still no avail.
 
-- Update
Forgot to mention that I'm trying to uninstall the program 7zip.install
And when I tried the Chocolatey Gui it did removed it silently from Programs and Features.

Is this a known bug? Or am I doing something wrong?
 Thx in advance.

**Comment by ferventcoder** [comment]
> But it still prompt the Yes/No question regards to AutoUninstaller.
> And it keeps waiting for 30 seconds untill timeout.

If you include the full log I would be able to tell you that the underlying software probably doesn't have a quiet uninstall and it's asking you if it is okay to run that (which will pop up the uninstallation UI for you to walk through).

Because it is timed out as you passed in `-y`, then that is expected behavior. You are confirming everything that can be done without user input with `-y`. If we were to use that to run possible blocking operations, that would break a LOT of things. Thus why you as a user get an option to have it run, but it won't automatically pop up. HTH

**Comment by ferventcoder** [comment]
It's meant to provide a better user experience for you when you are interactively sitting there with it. Well over 60-80% of the use cases of Chocolatey do not have an end user running choco, rather automation of some sort.
