### ISSUE TITLE
parameter 'file' Cannot convert value to type System.String

### ISSUE THREAD

**Issue by elig0n** [chocolatey/choco#2080]
I was trying to upgrade some packages and got this:

    > choco upgrade copyq
    Chocolatey v0.10.15
    Upgrading the following packages:
    copyq
    By upgrading you accept licenses for the packages.
    
    You have copyq v3.10.0 installed. Version 3.12.0 is available based on your source(s).
    Progress: Downloading copyq 3.12.0... 100%
    
    copyq v3.12.0 [Approved]
    copyq package files upgrade completed. Performing other installation steps.
    Automatically start with Windows
    Create desktop icon
    ERROR: Cannot process argument transformation on parameter 'file'. Cannot convert value to type System.String.
    The upgrade of copyq was NOT successful.
    Error while running 'C:\ProgramData\chocolatey\lib\copyq\tools\chocolateyInstall.ps1'.
     See log for details.
    
    Chocolatey upgraded 0/1 packages. 1 packages failed.
     See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
    
    Failures
     - copyq (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\copyq\tools\chocolateyInstall.ps1'.
     See log for details.

which looks similar to [#574](https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/574)

**Comment by PiotrGen** [comment]
Very not sure about this, best would be to have reproduction environment. But overview that chocoolateyInstall.ps1. There are some limiations in string size. Maybe, you are trying to load file that exceeds string capacity, If yes maybe you need to modify it to use some data structure instead.

**Comment by AdmiringWorm** [comment]
@PiotrGen the issue you linked to and the problem you are seeing is not related, your problem is that there may be multiple installers in the package (one from the old version, and one from the new version).
I went into more detail about this in the following issue: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1351.

However, this is a package related issue and not a choco issue. As such, to get that fixed, you will need to contact the maintainer of the package and ask them to correct the package. (You can contact the maintainer by navigating to the package page, then click on `Contact Maintainer(s)`, or if they have a package source listed you can use that link instead to create an issue)
