### ISSUE TITLE
Choco complains about a pending reboot on all of my systems, even after many reboots #1798

### ISSUE THREAD

**Issue by StewAlexander-com** [chocolatey/choco#2107]
Happening with every requested download, same issue reported in #178 

λ choco install choco-cleaner
Chocolatey v0.10.15
2 validations performed. 1 success(es), 1 warning(s), and 0 error(s).

Validation Warnings:
 - A pending system reboot request has been detected, however, this is
   being ignored due to the current Chocolatey configuration.  If you
   want to halt when this occurs, then either set the global feature
   using:
     choco feature enable -name=exitOnRebootDetected
   or pass the option --exit-when-reboot-detected.

**Comment by StewAlexander-com** [comment]
Keeps me from upgrading anything

**Comment by ferventcoder** [comment]
As you were creating an issue, was there not text that laid out what we need in a bug report? Please include detailed logs

**Comment by ferventcoder** [comment]
Hi @StewAlexander-com 
I see you closed this without any response to my query. Going to assume you are no longer experiencing this and put invalid label on this.

**Comment by StewAlexander-com** [comment]
To much hassle to update ticket with template, system was held up as needed a reboot w/ software install … reboot cleared msg

**Comment by ferventcoder** [comment]
@StewAlexander-com understood. However, for us to be able to help folks having issues, we need to see details - 90% of issues are environmental and we can't recreate someone else's environment - the logs and things that are asked for give us clues into what the actual issue is so we can implement fixes and make the product better. 

Something to keep in mind if you file future issues.

**Comment by StewAlexander-com** [comment]
Understand your requirements, and will follow next time...
