### ISSUE TITLE
Choco pin command should also pin ".install" packages when the alias is used

### ISSUE THREAD

**Issue by rcdailey** [chocolatey/choco#2151]
Suppose I have the following local packages:

* nodejs
* nodejs.install

When I run this command:

    choco pin add -n nodejs

It does not also pin `nodejs.install`, but I believe it should. Instead, I have to run the pin command again to explicitly pin `nodejs.install`:

    choco pin add -n nodejs.install

Please make the `pin` command also pin the `.install` version of the package when the alias (non-install) name is used.

**Comment by TheCakeIsNaOH** [comment]
I think there are two forms this could take.

First, a `--include-dependencies` switch could be added, so any dependencies of the named package would also be pinned.

Second, to implement this without also affecting packages dependencies with dependencies for other reasons (e.g. most people would not want `vcredist140` pinned because they pinned something that depends on it), I think virtual packages would be required first. see #858

**Comment by TheCakeIsNaOH** [comment]
This looks like it duplicates #2523, I'm not sure which one should stay open.

**Comment by pauby** [comment]
Lets keep #2523 open and close this one.
