### ISSUE TITLE
Dependency has exemption expected behaviour and request

### ISSUE THREAD

**Issue by MANICX100** [chocolatey/choco#2265]
I am trying to get
https://community.chocolatey.org/packages/imazing/2.13.8
approved with an exemption. This exemption is needed due to dotnetfx needing a reboot.

### What You Are Seeing?

https://gist.github.com/choco-bot/27aa731128785ace006207c3a654d7a4

### What is Expected?

Shouldn't the package be automatically exempt if its dependencies require a reboot? Or is the concern that that would be open to abuse with unchecked packages deliberately specifying dependencies as a workaround. 

### Output Log
https://gist.github.com/choco-bot/27aa731128785ace006207c3a654d7a4

**Comment by gep13** [comment]
@MANICX100 thanks for reaching out.  As noted in the issue template that hopefully you got a change to read, this repository is not the correct place to raise issues related to individual packages.  As such, I am going to go ahead and close out this issue here.

Regarding your package though, it is currently in the "Waiting for Maintainer" state:

![image](https://user-images.githubusercontent.com/1271146/117614091-b6b11480-b15f-11eb-8dae-6d5827bf72c1.png)

meaning  that you as the maintainer, need to take an action.  The action here is for you to request an exemption of your package from the package-verifier.  This can be done via the package page, while logged into community.chocolatey.org.  There is not currently as system in place that would automatically exempt a package, based on its dependencies., this is an action that needs to be performed by a human moderator.

**Comment by MANICX100** [comment]
Hi  Gary,

Thanks for your response. I couldn't see a link to contact the verifier so
I have contacted site admins. If this is wrong, please advise.


Kind regards,

--Dan Kendall

**Comment by AdmiringWorm** [comment]
@MANICX100 when you are logged in and look at the package page, you should set a box where you can write text into.
This is where you request an exemption, and the reason why you request the exemption (this box is used to talk/respond to moderators).
