### ISSUE TITLE
Powershell: Cannot overwrite variable ChocolateyVersion because the variable has been optimized

### ISSUE THREAD

**Issue by alfredonodo** [chocolatey/choco#2280]
Hi,
I'm using chocolatey since its first days. Generally, I use chocolatey inside a powershell script that installs it and installs packages. Recently, I do not exactly from which version, I have a problem with powershell 5.5 (windows 10 build 19041).
I get:
```
iex : Cannot overwrite variable ChocolateyVersion because the variable has been optimized. Try using the New-Variable
or Set-Variable cmdlet (without any aliases), or dot-source the command that you are using to set the variable.
At script.ps1:88 char:2
+     iex ((New-Object SystemNet.Webclient).DownloadString('https://chocolate ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (ChocolateyVersion:String) [Invoke-Expression], SessionStateUnauthorizedAcce
   ssException
    + FullyQualifiedErrorId : VariableNotWritableRare,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

By following the install instructions, it works as expected.
`Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`

Even with the previous lines inside the script, I get the same error. Any idea?
Thank you

**Comment by vexx32** [comment]
That's super odd. The script itself only sets `$ChocolateyVersion` in its param block, so I don't see how you could run into an error with it trying to overwrite the variable value...

Does the script you're running this from already have/use a `$ChocolateyVersion` variable? Can you share the overall script you're using, or a sanitised version of it?

**Comment by alfredonodo** [comment]
Hi,
I found the problem, the script uses a variable named $ChocolateyVersion and modifies it. Now, it is fixed. Is there any recent change about this that I missed?
Thank you

**Comment by vexx32** [comment]
The script was recently updated, and as part of that some of the things that previously only were settable with environment variables were moved to a `param()` block declaration so that they can be set directly on calling the script as well.

Have to say I didn't really expect that to break anything, but I guess there's a first time for everything. 😂 

Glad you got it sorted, though! Not entirely sure how running it inside of another script would make it break in this way, though. PowerShell's generally pretty good about its scoping, so it's rather odd that a `param()` declaration failed due to another variable existing already.

**Comment by alfredonodo** [comment]
I'm using chocolatey since 2015 when I participated to crowdfunding.
The script had this line:
`$ChocolateyVersion=choco -v`
Up to 1-2 months ago, I do not know exactly, it worked without any problem. I did not know that the variable was reserved by chocolatey.

**Comment by vexx32** [comment]
It's not that it's reserved, really. Seems like due to the way you're calling the script, PowerShell attempts to overwrite your script's variable instead of just running the script in a new scope, like most scripts are run.

A "safer" way to run it might be something like this:
```powershell
Set-ExecutionPolicy Bypass -Scope Process -Force
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
$script = (New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')
& ([scriptblock]::Create($script))
```

It might be time for us to update our docs on this. I'm rather impressed we haven't hit an issue like this before now, tbh. Invoke-Expression runs the script in the current scope, so clobbering variables could well have caused issues in the past without folks noticing. 😬

**Comment by alfredonodo** [comment]
Hi,
I always used Set-ExecutionPolicy Bypass and then I executed the script from powershell. Moreover, I discovered the problem just last week, but it could be present since 1-2 months.
Thank you for the information.
