### ISSUE TITLE
auto sync doesn't work for internal repositories

### ISSUE THREAD

**Issue by nascentt** [chocolatey/choco#2327]
![choco auto sync](https://user-images.githubusercontent.com/1145722/130617844-0388306a-60e3-48d2-b781-cdf07a6ef10f.png)
![choco auto sync local](https://user-images.githubusercontent.com/1145722/130618075-15043388-a55f-4f22-b02e-9938b9805479.png)
(Yes this is C4B)
and "choco feature enable -n showAllPackagesInProgramsAndFeatures" is enabled on hosts 

I assume this is related to issue 2326, but it's possible the internal commands differ.

### What You Are Seeing?
choco list --lo never syncs manual upgrades
### What is Expected?
add/remove programs shows a newer version installed
the choco package for that version exists in interal repo
doing choco list --lo doesn't sync the package
(and choco sync uses global repo issue 2326)
### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
PLACE LOG CONTENT HERE - WE NEED _ALL_ DETAILED OUTPUT BASED ON THE ABOVE TO BE ABLE TO PROVIDE SUPPORT (YOU WILL FIND THAT IN THE $env:ChocolateyInstall\logs\chocolatey.log between the `=====`)
~~~

</p>

</details>

**Comment by TheCakeIsNaOH** [comment]
The automatic sync does two things only:
1. Tracks if a program has been uninstalled outside of choco. If a program has been uninstalled, it will remove the package.
2. Tracks if a program has been upgraded outside of choco. If a program has been upgraded, it will update the registry information so the program can still be uninstalled by the automatic uninstaller.  It does not change the version of the Chocolatey package, it only updates the information for the automatic uninstaller.

See: https://docs.chocolatey.org/en-us/features/package-synchronization/automatic-sync#more-details-on-external-upgrades

Also, since this is for a licensed feature, it probably should go over in the repository for licensed feature issues:
https://github.com/chocolatey/chocolatey-licensed-issues/issues

**Comment by nascentt** [comment]
" It does not change the version of the Chocolatey package, it only updates the information for the automatic uninstaller."
So its by design.  Oh god that's depressing.

it means some packages stay perpetually out of date as doing choco upgrade will either do nothing if the application is always open, or force close the program (if the package was designed that way).

**Comment by TheCakeIsNaOH** [comment]
Closing as the question is answered.
