### ISSUE TITLE
Setup Coveralls for Github actions workflow

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#2441]
The Coveralls report for test coverage has been broken since 2019:
https://coveralls.io/github/chocolatey/choco

It was based on the tests run on the Appveyor build. Since the majority of the CI tests are now on Github actions, it would be good to setup Coveralls for Github actions. 
From: https://github.com/chocolatey/choco/pull/2433#issuecomment-960519180

Items:
- [ ] Remove Coveralls from the Appveyor build (or possibly remove the Appveyor build entirely?)
- [x] Validate that the Coveralls account is correctly signed in/linked to the `chocolatey` organization
- [ ] Add Coveralls upload to the `test.yml` workflow, specifically on the Windows build.
- [x] Add the Coveralls badge to the readme.

**Comment by gep13** [comment]
@TheCakeIsNaOH The UppercuT build already has functionality for doing this work, so part of me would be very curious to know why that functionality stopped working, before diving into doing it in a GitHub Action specific way.

**Comment by TheCakeIsNaOH** [comment]
@gep13 Fair enough. I'd personally suspect that it was either:
A. API token expired/revoked
B. Old version of the Nuget package used is incompatible with their current API.

I've looked into this a bit, and the Coveralls Github actions marketplace action only works with `lcov.conf` files. So it is probably better to either use (or update/replace) the uppercut functionality than try to convert the opencover format to lcov.

**Comment by gep13** [comment]
I don't remember seeing any output in any log to indicate that there was a problem updating the metrics, but I can experiment locally, to see if it works, and then we can make a decision about how to move forward.

**Comment by gep13** [comment]
@TheCakeIsNaOH ok, I "think" I know why this stopped working.  At some point, we moved the AppVeyor project for chocolatey/choco out from Rob's personal AppVeyor account into one specifically for Chocolatey.  When we did this, I don't believe the encrypted variable was being made available, since it wasn't possible to decrypt it.  This is seen in the logs:

<img width="969" alt="2021-11-06_17-13-26" src="https://user-images.githubusercontent.com/1271146/140618087-00036724-606b-4ebb-a0db-938412557158.png">

Where no additional work is done since the variable isn't there.

I have added the environment variable back in correctly, and the log now shows that it is at least attempting to do something:

<img width="1273" alt="2021-11-06_17-15-58" src="https://user-images.githubusercontent.com/1271146/140618116-796d0422-780d-44e4-90fc-59db6bea8b38.png">

But that it is failing, since it can't find any coverage metrics.  Looking at the build artifact on AppVeyor (and also when running locally) I can confirm that this is the case:

<img width="813" alt="2021-11-06_17-17-13" src="https://user-images.githubusercontent.com/1271146/140618163-825dcca5-e583-42e6-85e1-6183c94312dc.png">

When I run the build locally, I see the following in the build log:

<img width="1349" alt="2021-11-06_17-17-49" src="https://user-images.githubusercontent.com/1271146/140618178-c0ab6595-ec67-42c6-963e-5f729bca194b.png">

So the unit tests are running, but for some reason, the coverage statistics aren't being created.

I have seen this problem before, but I don't remember off hand how to fix this.

@AdmiringWorm do you have any suggestions on what is going on here?

**Comment by AdmiringWorm** [comment]
@gep13 I tried a few things to make it work, however everything I knew that could help the situation did not have any effect at all.

I couldn't even get the coverage report from the last known time we got a report (0.10.15 tag), and the only thing that I actually found to work was to upgrade the OpenCover executable located in `lib/OpenCover` to the latest version.
After that was updated, we had a coverage report again (at least locally), without any other changes needed.

**Comment by gep13** [comment]
Did you update to the latest version of OpenCover?

**Comment by AdmiringWorm** [comment]
Yeah, I did update it to the latest version.

**Comment by gep13** [comment]
@TheCakeIsNaOH thanks to @AdmiringWorm suggestion, I have been able to get the code coverage working again via the UppercuT build, and the metrics are now updating on coveralls.io:

https://coveralls.io/github/chocolatey/choco?branch=develop

I think the only thing remaining here would be to decide whether we need to keep the AppVeyor build.

**Comment by TheCakeIsNaOH** [comment]
> the metrics are now updating on coveralls.io:

Question on these, are these unit tests, integration tests, or both? And is there a way to check that everything is included?

> I think the only thing remaining here would be to decide whether we need to keep the AppVeyor build.

IMHO, let's keep it for the moment, now that the GH Actions workflow for running the integration tests is only running on a schedule instead of on every push and pr. So there is still a check in the PR workflow to validate that the integration tests are ok. 

If it is ending up taking too long to run the Appveyor build as a PR check, then let's just remove it entirely in that case.

**Comment by AdmiringWorm** [comment]
> Question on these, are these unit tests, integration tests, or both? And is there a way to check that everything is included?

Just checked, the coverage is only used for the unit tests. The integration tests are not included in the metrics.
The only way to check what is included is to look at the build script output on AppVeyor.

> I think the only thing remaining here would be to decide whether we need to keep the AppVeyor build.

I would say to keep the AppVeyor build, we may consider moving the coverage to GH Action eventually though, but not in the form we currently have.
If we move it to GH Action, we can make use of the Coveralls action that supports creating coverage reports in parallel (with a few modifications), running on pull requests and without the need to specify the Coveralls token itself.
We can not upload coverage reports from both AppVeyor and GH Action though.

**Comment by gep13** [comment]
So, assuming that we are going to continue with AppVeyor build, and we will use that for uploading the Coveralls report, there is nothing left to do on this issue, right?

**Comment by TheCakeIsNaOH** [comment]
Yup, I think we are done with this issue.
