### ISSUE TITLE
Copy-Item : Access to the path is denied

### ISSUE THREAD

**Issue by mattany** [chocolatey/choco#2485]
When trying to install chocolatey according to the instructions on the site, I get multiple copy errors when running from an elevated (Administrator) powershell. I think it could be related to the fact that my C: drive is mounted as NTFS.

[Attached is the log](https://github.com/chocolatey/choco/files/7697148/pslog.txt)

**Comment by vexx32** [comment]
@mattany thanks for the report! Apologies for the time taken to get to this issue. 

Are you still having this issue? If so, please fill out the [issue template](https://github.com/chocolatey/choco/issues/new?assignees=&labels=&template=zReportIssue.md) so we have the necessary context to determine what's going on here.

Also, are you using an antivirus? If so, which one? I've occasionally noted that some antivirus solutions will occasionally cause file copy operations to trip over, seemingly because it slows the file copy down as it tries to scan all the files being copied.

If this is the case, sometimes simply clearing out the target directory and retrying the copy is sufficient.

**Comment by pauby** [comment]
Due to this issue being stale, I'm going to go ahead and close it. We can always re-open it again if needed.
