### ISSUE TITLE
Source switch doesn't do anything on choco list --lo

### ISSUE THREAD

**Issue by nascentt** [chocolatey/choco#2545]
### What You Are Seeing?

**choco list --lo** outputs all installed packages.  Using **--source** switch to specific the repo doesn't affect **choco list --lo**
This means there's no way to get a list of the packages installed on a host from a specific repo the way you can for choco outdated

### What is Expected?
The number of packages returned from **choco list --lo** is the same as **choco list --lo --source** which means source is ignored for **--lo**  queries
Using **choco list --lo --source** for a source that zero packages have been installed from, still returns a full **choco list --lo** output

This means it's only possible to see which packages are installed from a specific source with **choco outdated**, and not **choco list --lo**

### How Did You Get This To Happen? (Steps to Reproduce)
**choco list --lo --source reponame**
<p>
</details>

**Comment by gep13** [comment]
I am not sure if I follow what you are trying to achieve here.

The command `choco list --lo`, in full form means `choco list --local-only`, i.e. it will return you a list of all the packages that are currently installed locally on the machine.

Chocolatey doesn't track _where_ a package has been installed from, so there is no way to do the equivalent of

> tell me all the packages that are currently installed which came from this specific source

In part, this is due to the fact that it is possible that the same package and package version can exist on one or more sources.

I am struggling to understand what the use case for this type of query is.  Can you expand on this?

On the other hand, `choco outdated` is about telling you, based on all of the sources that you have available, are there newer package versions available, based on the package versions that you currently have installed.

It is possible to limit the scope of this query to just one specific source, i.e. `choco outdated --source https://community.chocolatey.org/api/v2` which is basically saying...

> are there any packages on the Community Repository that have a higher package version than the package version currently installed on this machine

**Comment by pauby** [comment]
This is expected behaviour.

`choco list -lo` is where you specify the source for the list is local only. `choco list --source` is where you would list packages _from a specific source_.

These switches should either be mutually exclusive.

**Comment by nascentt** [comment]
> Chocolatey doesn't track where a package has been installed from, so there is no way to do the equivalent of

Ok, that's a pity but makes sense.  Thanks.

The --source switch existing in the choco list --help implied that it was possible.  I guess the help output should specific this can't be combined with the --lo switch

**Comment by gep13** [comment]
@nascentt just to make sure we are on the same page, you are talking about this section?

```
 -s, --source=VALUE
     Source - Source location for install. Can use special 'webpi' or
       'windowsfeatures' sources. Defaults to sources.

 -l, --lo, --local, --localonly, --local-only
     LocalOnly - Only search against local machine items.
```

If so, then I agree.  We should update that section to make it clear that those parameters are mutually exclusive.

**Comment by pauby** [comment]
For reference, doc issue [raised here](https://github.com/chocolatey/docs/issues/362).
