### ISSUE TITLE
Let choco install to C:\ProgramData\chocolatey\ *without* admin privileges.

### ISSUE THREAD

**Issue by alexchandel** [chocolatey/choco#259]
I don't like running in admin, and I think most people feel the same. It exposes the user to any number of security risks. And no one can claim that chocolatey is bug-free. In terms of not running as admin/root, systems like OS X's homebrew are great about this; it runs as a user, and thus can't harm the system. It can't even hurt other things installed into `/usr/local/` with higher permissions.

There should be a feature that makes `C:\ProgramData\chocolatey\lib\` writable by some non-admin users, or all users. For self-contained packages (as all packages should be), this suffices to extract the package into `C:\ProgramData\chocolatey\lib\package-name\` and let chocolatey create shims.

**Comment by ferventcoder** [comment]
The beauty of osx is that you can do a lot without sudo. The thing with Windows is you can't do the same. 

The beauty of Chocolatey is that you are free to choose a location that doesn't require admin rights.

**Comment by ferventcoder** [comment]
Location to install choco that is

**Comment by ferventcoder** [comment]
Since it is impossible to install to `c:\programdata` without administrative privileges, I'm going to close this as a non-issue. 

This would also possibly introduce security issues. But I mentioned that the install location of Chocolatey is completely configurable, and one can make the decision of where to install Chocolatey based on an environment variable - https://github.com/chocolatey/choco/wiki/installation#before-you-install

**Comment by ferventcoder** [comment]
Installing it to your custom location gives you complete control over security settings and being able to run choco as a non-admin.
