### ISSUE TITLE
Icons on fileshare repo

### ISSUE THREAD

**Issue by barjonas** [chocolatey/choco#2592]
I'm starting on my Chocolatey journey by using a shared directory as a repository. I have an install script which adds this repository using an environment variable and build scripts which push to the repository in the same way. The literal URL could end up varying between machines. This does not appear to leave any option for hosting icons. `<iconUrl>` does not support relative paths. That element is deprecated in the [latest nuspec](https://docs.microsoft.com/en-us/nuget/reference/nuspec#iconurl) spec anyway, but choco does not appear to support the newer `<icon>` element. If it did, it could be a great solution to my particular scenario.

I can see how this would add complexity to the tooling. The web repository would have to know how to maintain its own cache, and each client probably would too. But, on the other hand, part of the attraction to a package manager is their self-contained nature. This would make for more deterministic behavior than relying on multiple external CDNs etc. It would also make [the documentation](https://docs.chocolatey.org/en-us/create/create-packages#package-icon-guidelines) much simpler.

**Comment by gep13** [comment]
@barjonas Chocolatey forked the nuspec format that is used, so we don't follow along exactly with what NuGet.exe (the link that you provided does), so just because `iconUrl` is deprecated there, doesn't mean that it is deprecated in choco.exe.

The ability to support embedded icons in a package is definitely something that we _want_ to have, but as you say, this is something that will require changes both from a repository (community.chocolatey.org) stand point, as well as within choco.exe as well.

We have a tracking issue regarding the upgrade to the latest NuGet assemblies, which will likely encompass the ability to use embedded icons:

https://github.com/chocolatey/choco/issues/508

Can I suggest that you follow that issue for updates on this.

For now, I am going to close out this issue.

@ryanrichter94 this is another example of why we need this: https://github.com/chocolatey/docs/issues/374

**Comment by Schroedingers-Cat** [comment]
> We have a tracking issue regarding the upgrade to the latest NuGet assemblies, which will likely encompass the ability to use embedded icons:
> 
> #508

@gep13 with the referenced issue closed by v2.0, can we now use embedded icons?

**Comment by pauby** [comment]
> @gep13 with the referenced issue closed by v2.0, can we now use embedded icons?

Embedded icons are not supported. There is no timescale for when it will be implemented.
