### ISSUE TITLE
useRememberedArgumentsForUpgrades not remembering --version argument

### ISSUE THREAD

**Issue by Germs2004** [chocolatey/choco#2707]
### What You Are Seeing?
Running these commands will install filebot 4.7.9, but then the upgrade will update it to 4.9.6, even though I had useRememberedArgumentsForUpgrades enabled.
```
choco feature enable -n=useRememberedArgumentsForUpgrades
choco uninstall filebot
choco install filebot --version=4.7.9
choco upgrade filebot (same problem with choco upgrade all)
```

### What is Expected?
Since useRememberedArgumentsForUpgrades is enabled, the upgrade command should remember the "--version=4.7.9" argument for that package, and NOT upgrade that package to a later version.  If the user specified a version during the initial package install, they must have had a reason not to let chocolatey install the latest version, so the upgrade should respect the pinned version.  The upgrade output should mention that a newer package is available but it was skipped due to the pinned version argument.

**Comment by TheCakeIsNaOH** [comment]
The `--version` argument is not one of the arguments that is remembered. I'd give you a list of what arguments are remembered, but that does not exist outside the Chocolatey source code yet: https://github.com/chocolatey/docs/issues/404

Instead of remembering `--version` to prevent upgrades, the method Chocolatey CLI uses to prevent upgrade of a specific package is the `pin` command. There is not a way to pin a package during install, so you currently would have to run two choco commands, but there is an issue open to add that here: https://github.com/chocolatey/choco/issues/798

**Comment by Germs2004** [comment]
Thank you, I think pin will take care of the problem.  Since there's an issue to update the documentation already, I'll close this issue.
Perhaps Chocolatey should automatically pin packages when they're installed with a version specified, or output a message during package installation warning the user that they need to pin the version if they want to keep it.

**Comment by TheCakeIsNaOH** [comment]
> Perhaps Chocolatey should automatically pin packages when they're installed with a version specified

This would be a breaking change, so there most likely would have to be benefit to most parties in doing this. Personally, due to my use cases, I would rarely want this to happen.

> output a message during package installation warning the user that they need to pin the version if they want to keep it.

This sounds like it could be reasonable addition, maybe if other people could chime in?
