### ISSUE TITLE
chocolatey.infrastructure.app.commands.ChocolateyTemplateCommand

### ISSUE THREAD

**Issue by Pymann** [chocolatey/choco#2725]
For every command occurs:

Chocolatey v0.10.15 Business
The registered delegate for type IEnumerable<ICommand> threw an exception. Der Typ "chocolatey.infrastructure.app.commands.ChocolateyTemplateCommand" in der Assembly "choco, Version=0.10.15.0, Culture=neutral, PublicKeyToken=************" konnte nicht geladen werden.

But only on one pc?
Other pcs run fine.

I have no idea how you could reproduce it...

**Comment by Pymann** [comment]
Somehow two installtions were performed.

**Comment by gep13** [comment]
@Pymann I am not sure I follow what you are describing, but I am glad that you were able to get this resolved.

Since you have a Business license, for any future problems, it would be best to reach out to support.  If you run the `choco support` command, you will get details for how this can be done.
