### ISSUE TITLE
Chocolatey error/success message confusion

### ISSUE THREAD

**Issue by paul-hammant** [chocolatey/choco#2803]
![image](https://user-images.githubusercontent.com/82182/186111906-736623b5-9216-42dd-a5f6-78e23f0006d9.png)

Tried three time, couldn't delete/replace the exe based on permissions, communicated all that in red.

Ended with a green "success" message  which belies the nine lines that came before it.

Yes, I was logged into my Windows admin account.

**Comment by pauby** [comment]
Before we can look at this, we need you to complete the issue template.

**Comment by TheCakeIsNaOH** [comment]
When Chocolatey upgrades a package, it backs up the files (in the Chocolatey install directory) from the previous version of the package. If the install of the next package version works without errors, then that backup is deleted. 

The error message you are seeing is that the backup of the previous version was unable to be deleted because `chromedriver.exe` was unable to be deleted. This is presumably because `chromedriver.exe` was running at the time.

So the new version of the was successfully installed, but files from the package also still in the `lib-bkp` folder.

**Comment by paul-hammant** [comment]
Thanks. 

I suggest https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/NugetService.cs#L582 should be changed from:

```
"Attempted to remove '{0}' but had an error:".format_with(rollbackDirectory),
```

to:

```
"Attempted to remove rollback/backup version '{0}' but had an error, possibly because it was in use (check Task Manager):".format_with(rollbackDirectory),
```

**Comment by pauby** [comment]
I'm going to go ahead and close this issue as the template has now been used. We can always reopen it again if necessary.
