### ISSUE TITLE
Getting Cannot Combine Path Error

### ISSUE THREAD

**Issue by ryanrichter94** [chocolatey/choco#2865]
### What You Are Seeing?
When attempting to create a package running a `choco new --file "C:\temp\WIP\vlc.exe" --build-package --outputdirectory "C:\temp\WIP"` I am receiving the following error message. Cannot combine a path with ':' attempted to combine 'C:\temp\WIP\vlc.exe' with 'C:\temp\WIP'

### What is Expected?
The new package should be created an placed on C:\temp\WIP

### How Did You Get This To Happen? (Steps to Reproduce)
1. Have Chocolatey V 1.2.0 and chocolatey.extension V 5.0.0 installed 
1. Download the VLC exe and rename it vlc.exe
1. Place that vlc.exe in C:\temp\WIP
1. run the following command: `choco new --file "C:\temp\WIP\vlc.exe" --build-package --outputdirectory "C:\temp\WIP"`

### System Details
* OS Build: Windows Server 2022
* Windows PowerShell version: 5.1
* Chocolatey version: 1.2.0

Attempted running this with chocolatey V 1.1.0 and chocolatey.extension V 4.2.0 with no error.

### Output Log
<details>
<summary>Relevant chocolatey log output</summary>

<p>

~~~sh
2022-10-21 12:58:19,830 7200 [ERROR] - Cannot combine a path with ':' attempted to combine 'C:\temp\WIP\vlc.exe' with 'C:\temp\WIP'
2022-10-21 12:58:19,834 7200 [ERROR] - More Details: System.ApplicationException: Cannot combine a path with ':' attempted to combine 'C:\temp\WIP\vlc.exe' with 'C:\temp\WIP'
   at chocolatey.infrastructure.filesystem.DotNetFileSystem.combine_paths(String leftItem, String[] rightItems)
   at chocolatey.infrastructure.app.services.TemplateService.generate(ChocolateyConfiguration configuration)
   at chocolatey.infrastructure.app.runners.GenericRunner.run(ChocolateyConfiguration config, Container container, Boolean isConsole, Action`1 parseArgs)
   at chocolatey.infrastructure.app.runners.ConsoleApplication.run(String[] args, ChocolateyConfiguration config, Container container)
   at chocolatey.console.Program.Main(String[] args)
2022-10-21 12:58:19,835 7200 [DEBUG] - Exiting with 1
~~~

</p>

</details>

### Related Info.
- [ZenDesk Ticket](https://chocolatey.zendesk.com/agent/tickets/15670)

**Comment by corbob** [comment]
> @ryanrichter94 as far as I am aware, the `--file` parameter for the `new` command is a licensed only feature, and is not available in open source. And so I think this should be on the licensed issues repository?

The really weird part about this issue is I have been able to replicate it, and also not replicate it. The only place I've been able to consistently see this error is on Open Source Chocolatey. See the screen shots below...

Chocolatey 1.1.0 only:

![image](https://user-images.githubusercontent.com/30301021/197290875-5f32e042-34d9-4d0b-8331-e64bf244069a.png)

Chocolatey 1.1.0 with Chocolatey Licensed Extension 4.2.0:

![image](https://user-images.githubusercontent.com/30301021/197290929-38e1d90c-1900-4f67-8172-cf6d772434de.png)
Note with this one that it didn't work, then after a few attempts suddenly it did...

Chocolatey 1.2.0 with Chocolatey Licensed Extension 5.0.0:

![image](https://user-images.githubusercontent.com/30301021/197291031-5ba931c5-8e48-4126-8d86-c2420bd33b88.png)
Note that this one is somehow working.

All of this to say, I have no idea where or what is causing the issue, but it does appear to occur every time you try it in CLI, so I imagine fixing it there should solve it in Chocolatey Licensed Extension 🤷

**Comment by ryanrichter94** [comment]
To elaborate on this issue. With the release of [Chocolatey V 1.2.0](https://docs.chocolatey.org/en-us/choco/release-notes#october-19-2022) we added the ability for OSS chocolatey to load officially signed extensions. When Chocolatey V 1.2.0 is loaded with the chocolateygui.extension package installed. Chocolatey tries to interpret the chocolateygui.extension DLL and ends up reverting to using the OSS Chocolatey command set. 

This is why even though this touches licensed components of Chocolatey. The root issue is found within OSS Chocolatey.

**Comment by corbob** [comment]
An idea that may help with extension related troubleshooting might be if we can somehow list the file that assemblies are housed in. Either during the registration of commands (ie: `registered command 'new' from assembly 'choco' at 'C:\ProgramData\chocolatey\choco.exe'`), or just before that when it identifies that it found an assembly to load from.

**Comment by ryanrichter94** [comment]
Their are currently 2 workarounds if you are a licensed customer expernicing this issue.

1. Uninstalling the chocolateygui.extension package `choco uninstall chocolateygui.extension -y` This remove the other DDL that is causing CLI to look at it and revert to OSS functionality.
2. Downgrade the chocolatey and chocolatey.extension packages to the previous versions. `choco install chocolatey.extension -y -f --version 4.2.0 --allow-downgrade` `choco install chocolatey -y -f --version 1.1.0 --allow-downgrade` The bug was introduced in chocolatey V 1.2.0 but the new chocolatey also came with a bundled update of the chocolatey.extension package. Hence both need downgraded to achieve a supported state.
