### ISSUE TITLE
Allow to run pre-execution/post-execution script

### ISSUE THREAD

**Issue by Starmania** [chocolatey/choco#2869]
## Is Your Feature Request Related To A Problem? Please describe.

Apps block all socket and PowerShell connection, and only possibility to bypass that is to disable the app

## Describe The Solution. What is needed?
The possibility to execute a PS1 file where variables are set (to check admin perms, context (what command is executed), with choco module imported and the possibility to change the command executed

## Why is it needed
You could trigger script as I say using event trigger and schedule task but it is not a default option, you need GPO to configure the thing, only include in Windows Pro and you have no context, such as choco has no result of scripts result

_I can't preview the Issue and can't see if I do mistake, so when this line dissapear, that I will be sure of the issue_

**Comment by Starmania** [comment]
This is a variation of #1185, where pre/post script where executed before **almost any** command (outdated, push...)

**Comment by pauby** [comment]
@Starmania What you are proposing it not clear. Hook scripts already exist that can do this. What are you proposing that is different?

**Comment by Starmania** [comment]
A picture is worth 1000 words so ![IMG_20221026_134421.jpg](https://user-images.githubusercontent.com/52313983/198017770-b1f32d23-c7e1-45cb-aaa2-716bb8d39c50.jpg)![IMG_20221026_134409.jpg](https://user-images.githubusercontent.com/52313983/198017781-2e3c28dc-bfcb-4d60-bb9e-7f96b22d28df.jpg)

**Comment by pauby** [comment]
That's crystal clear now! Thank you.

We're not looking to expand when hook scripts run within open-source Chocolatey CLI. The functionality that has been added covers the majority of uses cases that open-source users would need.

But we will be adding this functionality to licensed versions of Chocolatey CLI in future.

As this isn't something we plan to do here, I'll go ahead and close this issue. We can reopen it if necessary.

**Comment by TheCakeIsNaOH** [comment]
@Starmania as an alternative, you could investiage creating a script that would wrap Chocolatey, so it would disable this other software, then running Chococolatey CLI with the arguments provided to the script, then enable this other software once Chocolatey CLI finishes running.

**Comment by tapika** [comment]
I've added into `swupd choco` fork support for custom `psrun` command. Theoretically it does want was requested by this ticket.

Main feature:
https://github.com/tapika/swupd/commit/f11420ad0f42aa97dc3bc26a44503e8f645c8a01

More integration tests:
https://github.com/tapika/swupd/commit/1b2b2f4474943c29792190f90716979f1cebe8c3

My fork however is based on .net core 3.1, so it's slightly different than normal `choco`.

But running this command requires package to be installed, otherwise it cannot be executed.
By default my `choco` uses local directory, but you can pinpoint to `choco` installation using `--instdir`.

If you have any further question, maybe create ticket in here:

https://github.com/tapika/swupd/issues
