### ISSUE TITLE
0.9.9.6 - "Object reference not set to an instance of an object" immediately during install/upgrade

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#292]
Trying to find the cause of this, but first noted by this discussion: https://groups.google.com/d/msgid/chocolatey/7d4081de-ce17-4d8f-b059-fdafbd298409%40googlegroups.com

``` sh
Upgrading the following packages:
jre8
By upgrading you accept licenses for the packages.
[ERROR] - Object reference not set to an instance of an object.
[DEBUG] - Exiting with 1
```

**Comment by Stevenpc3** [comment]
I have had issues similar to this when running dependency packages...  There were two cases that happened often (0.9.9.8);
1.  I had referenced an xml file that had bad elements and was corrupt
2.  A dependency package was reading values from a zip that window dropped from memory  or something, essentially the reference became null (it could have been permissions or scope or something).
We had a cmdlet that was called during a chocinstall script... that cmdlet then referenced and opened a zip in the choco pack that contains the chocoinstall script.  It took advantage of the lib folder. So, there was loading of a temp object into memory... if that makes any sense. :P  Anyway, there needed to be a safe load added to the reading of the packed item.

It could have something with reading jars.

Good luck!

Sorry for the poor examples.  The link to the group isn't working for me.

**Comment by ferventcoder** [comment]
Due to google groups not protecting email addresses, we had to close the group to members only. You would need to join the group first, then visit the link.

**Comment by CorbinIvon** [comment]
Hi @ferventcoder !

It looks like I'm experiencing a similar error and I think I can help narrow it down.

Here's my log for record. All personal data has been [[ REDACTED ]]:
[choco.error.log](https://github.com/chocolatey/choco/files/11919004/choco.error.log)

I believe that the issue lies within the NuGet.Protocol (Lines 167 & 169).

If "Object reference not set to an instance of an object." means anything to me, it's that an object that was created (probably from the resource created from NuGet.Protocol.Core) was being called, but got a NULL instead.

I'll see what I can find and continue posting here. What are your thoughts?

Thanks!

Corbin Meier.

**Comment by TheCakeIsNaOH** [comment]
@CorbinIvon I would suggest opening a new issue, as `NuGet.Protocol` is referenced by Chocolatey CLI starting in v2.0.0, so you are seeing some new problem.
