### ISSUE TITLE
vm image build pipelines failing because chocolatey installing windows update stuff and not installing tools requested as dotnetfx requires restart

### ISSUE THREAD

**Issue by Divya1388** [chocolatey/choco#3087]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

choco install azure-cli or choco install nuget.commandline (running chocolatey for first time on a vm created) always installs the following packages 

PS C:\Users\localadmin> choco.exe install azure-cli
Chocolatey v1.3.1
Installing the following packages:
azure-cli
By installing, you accept licenses for the packages.
Progress: Downloading chocolatey-visualstudio.extension 1.10.2... 100%
Progress: Downloading visualstudio2019buildtools 16.11.25.0... 100%
Progress: Downloading KB2919355 1.0.20160915... 100%
Progress: Downloading KB2919442 1.0.20160915... 100%
Progress: Downloading KB2999226 1.0.20181019... 100%
Progress: Downloading chocolatey-windowsupdate.extension 1.0.5... 100%
Progress: Downloading dotnetfx 4.8.0.20220524... 100%
Progress: Downloading chocolatey-dotnetfx.extension 1.0.1... 100%

The dotnetfx requires a restart and it is not installing any of the tools we require. We run the chocolatey installs in a azure devops pipeline and create a vm image out of it and because of this restart requirement, none of the tools are being installed  and this is failing our pipelines

### What is Expected?

azure-cli and nuget.commandline should have been installed

### How Did You Get This To Happen?

we have a internal nexus proxy repository which in turns proxy to the official chocolatey. I add the internal nexus proxy to the choco source and run choco install azure-cli -y

### System Details

* Operating System: Azure Windows 2016 Datacenter
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: v1.3.1 and v0.10.15 (behavior is the same)

### Installed Packages

```bash
PS C:\Users\localadmin> choco list -lo
Chocolatey v1.3.1
chocolatey 1.3.1
chocolatey-dotnetfx.extension 1.0.1
chocolatey-visualstudio.extension 1.10.2
chocolatey-windowsupdate.extension 1.0.5
4 packages installed. 

all the runs install chocolatey fresh
```

### Output Log

```bash
Chocolatey installed 6/6 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Installed:
 - kb2919355 v1.0.20160915
 - kb2999226 v1.0.20181019
 - dotnetfx v4.8.0.20220524
 - visualstudio2019buildtools v16.11.25.0
 - kb2919442 v1.0.20160915
 - visualstudio-installer v2.0.3

Packages requiring reboot:
 - dotnetfx (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.
Sending message 'PostRunMessage' out if there are subscribers...
Exiting with 3010
```

**Comment by pauby** [comment]
Can you go back to the original message and provide the chocolatey.log as requested?

**Comment by Divya1388** [comment]
Hey @pauby  sorry i missed this. I will check that sometime Friday and post it here. Thanks for looking in to this

**Comment by pauby** [comment]
There has been no response to this, so I'm going to go ahead and close it, but we can reopen it if necessary.

**Comment by flopezQM** [comment]
Hi, since 16/05/2023 at about 20H UTC, I started having the reboot issue in my pipeline when using `choco install php --version=7.4 --allow-downgrade -package-parameters='"/InstallDir:C:\tools\php"'`
Never had this issue with that step before. Also tried the `choco feature disable --name="'exitOnRebootDetected'"` beforehand but to no avail. Thanks

**Comment by pauby** [comment]
@flopezQM Just to be very clear, is Chocolatey exiting and not installing the packages, or are the packages being installed but the message appears?

**Comment by flopezQM** [comment]
@pauby Yeah, packages (php 7.4 in this case) are installed ok, but the message shows up at the end

**Comment by pauby** [comment]
@flopezQM That's intentional. The feature doesn't make the message go away. It just stops Chocolatey CLI exiting as soon as it detects a reboot is required.

**Comment by flopezQM** [comment]
@pauby Understood, the problem is that the pipeline fails and stops. And I didn't have that message before. See below:

- My pipeline step:
`- script: |
          choco feature disable --name="'exitOnRebootDetected'"
          choco install php --version=7.4 --allow-downgrade -package-parameters='"/InstallDir:C:\tools\php"'
        displayName: Use PHP version 7.4`

- Last good run task output (yesterday):

`php v7.4.0 [Approved]
php package files install completed. Performing other installation steps.
Uninstalling previous version of php...
C:\ProgramData\chocolatey\lib\php\php-8.2.5-nts-Win32-vs16-x64.zip.txt
The PATH environment variable already contains the directory 'c:\tools\php'. Removing...
Extracting 64-bit C:\ProgramData\chocolatey\lib\php\tools\php-7.4.0-nts-Win32-vc15-x64.zip to C:\tools\php...
C:\tools\php
Please make sure you have CGI installed in IIS for local hosting
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of php was successful.
  Software installed to 'C:\tools\php'

Chocolatey installed 2/2 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Finishing: Use PHP version 7.4
`

- Task output some minutes later when pipeline was retriggered:

`php v7.4.0 [Approved]
php package files install completed. Performing other installation steps.
Uninstalling previous version of php...
C:\ProgramData\chocolatey\lib\php\php-8.2.5-nts-Win32-vs16-x64.zip.txt
The PATH environment variable already contains the directory 'c:\tools\php'. Removing...
Extracting 64-bit C:\ProgramData\chocolatey\lib\php\tools\php-7.4.0-nts-Win32-vc15-x64.zip to C:\tools\php...
C:\tools\php
Please make sure you have CGI installed in IIS for local hosting
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of php was successful.
  Software installed to 'C:\tools\php'

Chocolatey installed 3/3 packages. 
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Packages requiring reboot:
 - vcredist140 (exit code 3010)

The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.
##[error]Cmd.exe exited with code '3010'.
Finishing: Use PHP version 7.4
`

**Comment by pauby** [comment]
What looks to be the issue is that the `vcredist140` package installer is exiting with 3010 which Chocolatey is passing back to your script. Your script interprets anything apart from 0 as a failure, so is failing.

There was a [new version of vcredist140 released yesterday](https://community.chocolatey.org/packages/vcredist140#versionhistory), which would correlate with the errors you started to see.

![image](https://github.com/chocolatey/choco/assets/12760779/6186d4e4-33de-48ce-8e4a-3f48ea16360a)

As it's a new version, it's unlikely to be installed on the runner, so your Docker container might not have it pre-installed already, so it is actually installing and needing a reboot.

You might want to look at the [`usePackageExitCodes`](https://docs.chocolatey.org/en-us/configuration#exit-codes)  feature. I haven't been able to reproduce your issue so I cannot test that.

**Comment by flopezQM** [comment]
@pauby I think totally correlates: adding 'choco feature disable --name="'usePackageExitCodes'"' to my pipeline step sorted out the issue. Thanks for your help.

**Comment by pauby** [comment]
Glad it worked. I will go ahead and close this issue.
