### ISSUE TITLE
Search does not use previously cached results

### ISSUE THREAD

**Issue by pauby** [chocolatey/choco#3125]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

When doing a call to `choco search` it does not re-use a previously cached results, unlike what is done when calling `choco install`.

### Describe The Solution. Why is it needed?

To keep it consistent with the results you would get with installations.

### Additional Context

N/A

### Related Issues

- [Clickup task](https://app.clickup.com/t/20540031/PROJ-517)

**Comment by gep13** [comment]
While working on [this issue](https://github.com/chocolatey/choco/issues/3183), it was identified that this issue could also be addressed at the same time.  This is due to the fact that by providing a `ChocolateySourceCacheContext` to all places that it is needed, to prevent a 1 second delay being applied to the outgoing query, the issue with the search queries not using the cached results, goes away.

Follow up issues will be created, and added to the 2.1.0 milestone to allow purging of the caches, as well as to allow skipping of the caches for certain queries.
