### ISSUE TITLE
Interact with Winget metadata

### ISSUE THREAD

**Issue by hantsy** [chocolatey/choco#3192]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

I installed docker desktop via choco command, but winget can recognize it and provide new version more quickly. So I updated it via winget, but choco can not recognized the new version installed.

### Describe The Solution. Why is it needed?

Interact with winget, 

* reading version metadata from Winget
* writing version metadata into winget 

In one world, if update via choco, should let Winget get the new version, if updated by Winget, choco also should know aware about it.

**Comment by pauby** [comment]
If you update the _software_, installed by Chocolatey CLI, with WinGet, then Chocolatey CLI does not see it, as it manages the package, not the software. The solution is to run `choco upgrade <PACKAGE NAME> --skip-powershell` when the latest package is available.

Chocolatey Licensed will update the package version to the version of the software automatically, if it has been updated outside of Chocolatey CLI.

This is expected behaviour.

**Comment by hantsy** [comment]
Ok, let's use example to explain this issue I encountered.

1. Docker desktop is installed by Choco cli, now it is updated to 4.20 by winget, but `choco list` show the latest version is 4.19, but my local installed version is updated to 4.20.

2. Another package `dotnet-sdk` installed by choco cli, it is updated to latest 7.0.300, but `winget list` still show its version 7.0.203, using `winget upgrade xxx` is no help.
