### ISSUE TITLE
Improve performance when upgrading all packages

### ISSUE THREAD

**Issue by TheCakeIsNaOH** [chocolatey/choco#3231]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

When a large number of packages (e.g. 300+) are installed on Chocolatey CLI v2.x, the `choco upgrade all` command takes quite a bit longer to run than it did on v1.4.0 

One large contributor to this is that Chocolatey now gets a list of all installed packages before every upgrade check, instead of only refreshing the list when a package upgrade happens. This check can take a while when a large number of packages are installed.

### Describe The Solution. Why is it needed?

Chocolatey should only get the list of all installed packages when required, instead of before every package outdated check. 

### Related Issues

- Issue #3183

**Comment by gep13** [comment]
> @crkinard said...
But the issue was 'resolved' in v2.1.0. 🙄

I think you might be referring to this issue:

https://github.com/chocolatey/choco/issues/3183

Which was indeed fixed in v2.1.0.  That issue was the result of a imposed 1 second delay on each HTTP request that was made by Chocolatey CLI, which had an impact on pretty much all the commands that Chocolatey CLi has.

This issue that @TheCakeIsNaOH has raised is specifically for the `choco upgrade all` command. where multiple listing of packages is done during the execution of the command, which results in the `choco upgrade all` command taking a noticeably longer time to complete compared to v1.4.0.
