### ISSUE TITLE
Builds failing on Ubuntu 20.04

### ISSUE THREAD

**Issue by regg00** [chocolatey/choco#3243]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Builds are failing on Ubuntu 20.04 with the following message from `build.sh`: 

> System.InvalidOperationException: Gitversion could not determine which branch to treat as the development branch (default is 'develop') nor release-able branch (default is 'main' or 'master'), either locally or remotely. Ensure the local clone and checkout match the requirements or considering using 'GitVersion Dynamic Repositories'

I think this commit by @gep13 is the issue: https://github.com/chocolatey/choco/commit/2bbe5d711ad1499fef0cb24b70ef4b87ff7fd505

### What is Expected?

Builds should complete successfully

### How Did You Get This To Happen?

1. Followed the official documentation here step by step: https://github.com/chocolatey/choco#other-platforms
2. Ran the build.sh script
3. Build failed

### System Details

* Operating System: Ubuntu 20.04-LTS
* Windows PowerShell version: N/A
* Chocolatey CLI Version: 2.0.1
* Terminal/Emulator: Windows Terminal with WSL

### Installed Packages

```bash
N/A
```

### Output Log

```bash
System.InvalidOperationException: Gitversion could not determine which branch to treat as the development branch (default is 'develop') nor release-able branch (default is 'main' or 'master'), either locally or remotely. Ensure the local clone and checkout match the requirements or considering using 'GitVersion Dynamic Repositories'
```

### Additional Context

I was able to work around the issue with the following patch on the GitVersion.yml file: https://github.com/regg00/ghaction-chocolatey/blob/cce39706d23de62308d4da8a0cec658823e9f91e/image/GitVersion.patch

**Comment by gep13** [comment]
@regg00 I am fairly sure that the issue is not with the commit that you linked to.

We build every commit on Linux, Mac and Windows on GitHub Actions, and the Linux OS is Ubuntu 22.04.2.

You can see the most recent builds here:

https://github.com/chocolatey/choco/actions/runs/5423219825

Can you confirm exactly how you grabbed the source code for the repository?

**Comment by regg00** [comment]
You're totally right.
I cloned the 2.1.0 tag with this command: `git clone --branch 2.1.0 https://github.com/chocolatey/choco.git`
When doing so, `git status` returns the following message:
```
Not currently on any branch.
nothing to commit, working tree clean
``` 

This is what messes up GitVersion and prevents the build from completing.
If I clone the repo with: `git clone https://github.com/chocolatey/choco.git` then the build is successful.

I'm not familiar with GiVersion so I don't really understand why cloning a specific branch break stuff.

**Comment by gep13** [comment]
GitVersion is a tool which asserts the current semantic version number for the repository.  It does this by  inspecting the history of the git repository, looking at the current branches, tags, commit messages, etc.  This asserted version number then flows into the build in order to stamp the generated choco.exe and other assemblies with the correct version number.

If you clone a specific tag, or commit, there isn't enough information present for GitVersion to correctly assert the version number, and therefore it fails.

That is why we checkout in this way:

https://github.com/chocolatey/choco/blob/d836138142e6b1e7a9b2e931faeb0c4d4fb4b6c2/.github/workflows/build.yml#L16-L18

This is working as intended, so I am going to go ahead and close out this issue, but we can continue the conversation if you have more questions/

**Comment by gep13** [comment]
@regg00 I haven't looked at that GitHub Action in a long time, so I can't remember exactly what it is doing, but I am wondering if the official Chocolatey Docker Image:

https://hub.docker.com/r/chocolatey/choco

Or the official tar.gz which we add as an asset to each GitHub Release:

https://github.com/chocolatey/choco/releases/tag/2.1.0

Would help in what you are trying to do.

If there is still a need to do an unofficial build of Chocolatey, it would be good to understand that need, to see if there is anything else we can do.

**Comment by regg00** [comment]
> GitVersion is a tool which asserts the current semantic version number for the repository.  It does this by  inspecting the history of the git repository, looking at the current branches, tags, commit messages, etc.  This asserted version number then flows into the build in order to stamp the generated choco.exe and other assemblies with the correct version number.
> 
> 
> 
> If you clone a specific tag, or commit, there isn't enough information present for GitVersion to correctly assert the version number, and therefore it fails.
> 
> 
> 
> That is why we checkout in this way:
> 
> 
> 
> https://github.com/chocolatey/choco/blob/d836138142e6b1e7a9b2e931faeb0c4d4fb4b6c2/.github/workflows/build.yml#L16-L18
> 
> 
> 
> This is working as intended, so I am going to go ahead and close out this issue, but we can continue the conversation if you have more questions/

Thanks a ton for the help on this.
