### ISSUE TITLE
Choco returns inconsistent version info for packages

### ISSUE THREAD

**Issue by o-l-a-v** [chocolatey/choco#3297]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

Choco 2.2.2 just got released, I have v2.2.0. It's also updated in the repositories:

* https://community.chocolatey.org/packages/chocolatey/2.2.2

I first check for outdated packages with `choco outdated`, says no packages are outdated.

![image](https://github.com/chocolatey/choco/assets/6450056/f22ae938-e0ba-46dd-8714-c19a4fb3954a)

I then try `choco search chocolatey --exact`, says newest version of Chocolatey is v2.2.0.

![image](https://github.com/chocolatey/choco/assets/6450056/417d5bab-3262-4013-bc03-0334c8f90287)

I then do `choco search chocolatey` which returns a lot of packages, also Chocolatey. Says latest version of Chocolatey is v2.2.2.

![image](https://github.com/chocolatey/choco/assets/6450056/a023ab9d-9013-411a-b484-2f9c800edbc0)

I then check the `chocolatey.log`, the API request when searching exact is:

```powershell
Invoke-RestMethod -Method 'Get' -Uri "https://community.chocolatey.org/api/v2/Packages()?`$filter=(tolower(Id)%20eq%20'chocolatey')%20and%20IsLatestVersion&semVerLevel=2.0.0"
```

![image](https://github.com/chocolatey/choco/assets/6450056/5932e40c-4af7-40f5-a14f-55d18699b9be)

It says v2.2.0 is the latest version. But if you add "not IsPrerelease" to the query, like the search without exact does, voila:

```powershell
Invoke-RestMethod -Method 'Get' -Uri "https://community.chocolatey.org/api/v2/Packages()?`$filter=(tolower(Id)%20eq%20'chocolatey')%20and%20not%20IsPrerelease%20and%20IsLatestVersion&semVerLevel=2.0.0"
```

![image](https://github.com/chocolatey/choco/assets/6450056/cfcd1dd2-3e42-4726-bb02-54d8fbe423a4)

### What is Expected?

I expect a consistent experience when searching and updating a package, with or without `--exact`. `choco` should use the API consistently to not get inconsistent results.

I also expect the API to return the latest non-prerelease version of a package, even if not specifying `not IsPrerelease`.

### How Did You Get This To Happen?

See first section.

### System Details

* Operating System: Windows 10 22H2 19045.3208
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 2.2.0
* Chocolatey Licensed Extension version: None
* Chocolatey License type: None
* Terminal/Emulator: None

### Installed Packages

```bash
Not relevant
```

### Output Log

```bash
Not relevant
```

**Comment by TheCakeIsNaOH** [comment]
@o-l-a-v I can reproduce this, where `choco search chocolatey --exact --source=https://community.chocolatey.org/api/v2` returns v2.2.0, not v2.2.2. However, this appears to be an issue with Chocolatey Community Repository, not with Chocolatey CLI.

**Comment by o-l-a-v** [comment]
@TheCakeIsNaOH 

I agree, the fault seems to be with the API of the community repository. Where do I create an issue for that?

That being said, the CLI passes different filters to the API when using '--exact' vs. not, ref 'not IsPrerelease'. So could be mitigated by the CLI too it seems.

**Comment by o-l-a-v** [comment]
It seems to return v2.2.2 with or without `not IsPrerelease` today, strange.

![image](https://github.com/chocolatey/choco/assets/6450056/38d0cce2-0ec9-40cf-9d7e-b4ac4118b177)

**Comment by pauby** [comment]
I can't reproduce this.

![image](https://github.com/chocolatey/choco/assets/12760779/5aea11a6-1c1e-439d-a167-ce0c1da866ea)

When there is a mismatch about what is in the Chocolatey Community Repository and what is reported by Chocolatey CLI, it's generally down to caching. It's something we are working on and mostly is not an issue, but does rear it's head every so often.

**Comment by o-l-a-v** [comment]
@pauby 

Cache where, in the API?

This is still a bug IMO, we just don't know what caused it.

And why not include `not IsPrerelease` in `--exact` search, as it seems to make a difference in edge cases?

**Comment by cobrabr** [comment]
I'm having the exact same problem with another package, `k-litecodecpackfull`:

![image](https://github.com/chocolatey/choco/assets/724969/f89a7981-967a-4ff3-808d-595f9fe6b7ea)

Funnily enough, Chocolatey GUI doesn't have this problem — I used the "Check for outdated packages (forced)" button and it successfully picked up this package as outdated:

![image](https://github.com/chocolatey/choco/assets/724969/15295631-b35b-4be3-9eb7-2f35520a6796)

I was trying to find a way to run the same "forced" check for outdated packages on the CLI, but `choco outdated --force` doesn't do anything.

**Comment by gep13** [comment]
> @o-l-a-v said...
>
> Cache where, in the API?

There are several layers of caching in play with Chocolatey and Chocolatey GUI.  Let me quickly recap them.  **NOTE:** The following assumes that you are using 2.x.x of both Chocolatey CLI and GUI.

1. One of the first things that Chocolatey GUI does on startup is to figure out which packages are currently outdated. This happens each time to open the application, although it is possible to control this action through a [feature](https://docs.chocolatey.org/en-us/chocolatey-gui/setup/configuration/features/prevent-automated-outdated-packages-check). So that this information doesn't have to be re-calculated each time, Chocolatey GUI caches the results in an xml file, which is read when the application loads.  This information is stored for a [configurable period of time](https://docs.chocolatey.org/en-us/chocolatey-gui/setup/configuration/settings/outdated-packages-cache-duration-in-minutes), and it can be forced to be recalculated using the  `Check for outdated packages (forced)` [button](https://docs.chocolatey.org/en-us/chocolatey-gui/user-interface/main-window/actions/check-for-outdated).  Additionally, you can manually purge this file using the [purge outdated packages](https://docs.chocolatey.org/en-us/chocolatey-gui/user-interface/settings/actions/purge-outdated-packages) button.
2. On top of the built in caching that Chocolatey GUI provides, Chocolatey CLI itself also caches the results of HTTP queries. By default, the results of these queries are stored within the `C:\ProgramData\ChocolateyHttpCache` folder.  To clear this cache, you can use the `choco cache` [command](https://docs.chocolatey.org/en-us/choco/commands/cache), or you can make use of the `--ignore-http-cache` option which is available on all Chocolatey CLI commands.
3. Then, at the website level (the API), there are a number of different caches in play.  For example, we have a shared key/value cache, as well as search index caching (which currently is web host dependent).  These caches are used when Chocolatey GUI, or Chocolatey CLI, make an HTTP request.  Part of the problem here, which @pauby alluded to above, is that the search index caching is done on a per web host basis.  As a result, it is possible to get one response from web host, and a different one from another web host.  This is something that we are actively working on correcting, but we don't have anything to share on this at the moment.  Typically, caching issues at this level tend to "fix themselves" after a period of time, once the cache expires, and the information is repopulated.

> @o-l-a-v said...
>
> I agree, the fault seems to be with the API of the community repository. Where do I create an issue for that?

Issues for the Chocolatey Community Repository would be raised here: https://github.com/chocolatey/home/issues

However, the issue that you are seeing it likely covered by this issue: https://github.com/chocolatey/home/issues/8 Feel free to add additional information to there.

@o-l-a-v said...
>
> Why not include not IsPrerelease in --exact search (and coho outdated and choco upgrade), as it seems to make a difference in edge cases?

I honestly do not believe that this is required.  Almost everywhere in Chocolatey, everything defaults to the stable version numbers.  You have to opt-in to get prerelease versions.  As such, explicitly stating `not IsPrerelease` should not be required on queries.  The differences that you are seeing is likely due to the cached values that are stored for the "normal" queries, compared to the lesser executed queries.  Eventually, both of these would result in getting the same result.

Hopefully the above helps to understand what is going on, and what the different caching solutions are in place for Chocolatey GUI and CLI.  Let me know if you have any questions about any of the above.

**Comment by o-l-a-v** [comment]
AFAIK this is not fixed, so please open again.

Going stale != Fixed.

**Comment by pauby** [comment]
@o-l-a-v As pointed out in the comments above, this is a caching issue which is related to https://github.com/chocolatey/home/issues/8.

> Going stale != Fixed.

The issue was waiting on your response. After no response to the previous two comments on 10 August and 10 September, the issue is closed automatically. This is the process we have in place for this repository.
