### ISSUE TITLE
Conflict of Python Executables in PATH after Chocolatey Installation

### ISSUE THREAD

**Issue by saoudi-h** [chocolatey/choco#3336]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

After installing Chocolatey, Python executables are added to the PATH environment variable. This causes conflicts when trying to run Python commands, as Windows prioritizes the Chocolatey executables.

### What is Expected?

I expect that Chocolatey installation does not interfere with existing Python installations. When I install Python after Chocolatey, it should not result in conflicts with Python commands, and Windows should correctly identify the installed Python version.

### How Did You Get This To Happen?

I already had Python installed before getting Chocolatey.
When I installed Chocolatey, everything worked fine.
But later, I decided to uninstall Python and use pyenv-win to manage my Python versions.
After uninstalling Python, I installed pyenv-win using Chocolatey.
Pyenv worked wonderfully, and I used it to install Python 3.10.5 with "pyenv install 3.10.5".
Now here's the problem: when I restarted my terminal and ran "python --version", nothing happened. No error message, no Python version.
I ran "where python," and the first line was "C:\ProgramData\chocolatey\bin\python," followed by "C:\Users\still.pyenv\pyenv-win\shims\python."
Chocolatey's Python took precedence over the real Python.
I figured this out by rearranging my environment variables – placing my Python installation on top of Chocolatey's – and that did the trick.
Now Python works great.

### System Details

* Operating System: 11
* Windows PowerShell version: 5.1.22621.1778
* Chocolatey CLI Version: 2.2.2
* Chocolatey Licensed Extension version: Chocolatey v2.2.2
* Chocolatey License type: ?
* Terminal/Emulator: CMD, PowerShell Core

### Installed Packages

```bash
chocolatey 2.2.2
chocolatey-compatibility.extension 1.0.0
chocolatey-core.extension 1.4.0
chocolatey-windowsupdate.extension 1.0.5
dart-sdk 3.1.0
gradle 8.1.1
KB2919355 1.0.20160915
KB2919442 1.0.20160915
KB2999226 1.0.20181019
KB3033929 1.0.5
KB3035131 1.0.3
mingw 12.2.0.3042023
neovim 0.9.1.20230531
pyenv-win 3.1.1
vcredist140 14.34.31938
vcredist2015 14.0.24215.20170201
```

### Output Log

```bash
The issue isn't related to Chocolatey's core functionality but rather to files exposed in its "bin" directory that can conflict with other software, including Python.
Installing Chocolatey first, followed by Python or similar tools, can result in these exposed files taking precedence, causing execution conflicts.
```

**Comment by JPRuskin** [comment]
Two parts to this, for me, though I may be misreading it:

> After installing Chocolatey, Python executables are added to the PATH environment variable.
> I expect that Chocolatey installation does not interfere with existing Python installations.

A fun/confusing bit to me is that Chocolatey CLI doesn't ship with a Python shim in the bin directory (or add it elsewhere), and it doesn't look like the `pyenv-win` package adds one - so Chocolatey CLI's installation _already_ doesn't interfere with existing Python installations... unless you install a package that adds a Python shim.

Did you install a Python package at some point, and then remove it without using `choco uninstall`?

> When I install Python after Chocolatey, it should not result in conflicts with Python commands, and Windows should correctly identify the installed Python version.

It's worth noting that we don't control the Python installer, or Windows. If the Python installer chooses to add itself to PATH last, this will happen.

To my knowledge we don't ensure or guarantee that Chocolatey's shims (e.g. the bin folder) are on PATH in any specific location or order, after the initial install. If you install other things at different times, the precedence may change - so this seems like an issue with your environment configuration to me. You are welcome to change the order of your PATH variable, we don't control that.

I don't think this is a bug but "systems (PATH) working as expected" - but if you could fill out reproducable steps (e.g. including details on how you initially installed Python, rather than just "already had Python installed") we may be able to help further.

**Comment by saoudi-h** [comment]
I redid my entire installation, and I couldn't reproduce the error, so it was probably a misunderstanding or mistake on my part. If that's the case, then I'm sorry for your time.

**Comment by gybson63** [comment]
https://disk.yandex.ru/d/bhy6EsnMHt8MgA
