### ISSUE TITLE
chocolatey-core.extension gets uninstalled with choco uninstall -x

### ISSUE THREAD

**Issue by joel-schaal** [chocolatey/choco#3341]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.
- [X] I confirm I am using **official**, and **not** unofficial, or modified, Chocolatey products.

### What You Are Seeing?

When I perform `choco uninstall -x -y 7zip` (7zip is listed as an example, many nuggets have the same result) the dependency `chocolatey-core.extension` is removed too, even though it is something provided with chocolatey itself.

Even if I pin `chocolatey-core.extension` , it is still removed (as well as the pin)

### What is Expected?

Core dependencies should not be removed when we remove the dependencies of a nugget

### How Did You Get This To Happen?

1. choco install -y 7zip
2. choco uninstall -x -y 7zip

### System Details

* Operating System: Windows 19045.3516
* Windows PowerShell version: 5.1.19041.3031
* Chocolatey CLI Version: 2.1.0
* Chocolatey License type: community

### Installed Packages

```bash
PS C:\Users\DWOS> choco list
Chocolatey v2.1.0
Boxstarter 3.0.0
Boxstarter.Bootstrapper 3.0.0
Boxstarter.Chocolatey 3.0.0
Boxstarter.Common 3.0.0
Boxstarter.HyperV 3.0.0
Boxstarter.WinConfig 3.0.0
chocolatey 2.1.0
DotNet3.5 3.5.20160716
dw-commons.extension 1.0.0
dw-hwmonitor 1.52.0
dw-scriptinstall 1.0.2
hwmonitor 1.52.0.20230901
intel-burn-test 3.2.0
intellijidea-ultimate 2022.3.1
maven 3.9.4
probe-control-center 1.0.0
```

### Output Log

```bash
"There was an error creating your issue: body is too long (maximum is 65536 characters)."
```

**Comment by AdmiringWorm** [comment]
@joel-schaal as the issue template mentioned, we need all the information from the output log, and if you could not include it in the issue itself upload this information to https://gist.github.com/ and link to it in the output log section.

Can you please do this, and update the initial issue with the link to this gist?

**Comment by joel-schaal** [comment]
[chocolatey.log](https://github.com/chocolatey/choco/files/13311760/chocolatey.log)

**Comment by pauby** [comment]
The version of Chocolatey CLI in the logs is not supported for open source. Can you upgrade to the latest 2.2.2 version and reproduce it?

**Comment by joel-schaal** [comment]
I updated chocolatey to 2.2.2 and reperformed the commands, the problem is still there. 
The logs look quite the same:
[chocolatey.log](https://github.com/chocolatey/choco/files/13312662/chocolatey.log)

**Comment by steviecoaster** [comment]
@joel-schaal  I believe this is expected behavior. The`chocolatey-core.extension` is _not_ provided as a part of Chocolatey.

when you Installed the `7zip` the following happend:

7zip evaluated that it needed the 7zip.install dependent package. The `7zip.install` package in turn took a dependency on `chocolatey-core.extension`, and the `chocolatey-core.extension` package itself took a dependency on `chocolatey-compatibility.extension`. After everything was said and done Chocolatey had installed the follow packages to satisfy the entire dependency tree along with the package you requested:

- 7zip
- 7zip.install
- chocolatey-core.extensioin
- chocolatey-compatibility.extension

When you issued the `-x` parameter on your install command you explicity told Chocolatey to `Uninstall dependencies when uninstalling package`, according to the help.

The portion of this that may need evaluated as a bug is when you say: `Even if I pin chocolatey-core.extension , it is still removed (as well as the pin)`. I believe _that_ may be unexpected behavior. But if the pinning of packages is not in play, I believe Chocolatey CLI is behaving as intended.
