### ISSUE TITLE
Capture Arguments for a Package during Install/Upgrade

### ISSUE THREAD

**Issue by SeanKilleen** [chocolatey/choco#358]
Per discussion from #357. 

Capturing any ~~installation~~ arguments from a given package at the time it is installed/upgraded will enable enhancements such as exporting package.config files and being able to recreate a chocolatey package setup.

This will also allow for automatic passing of "remembered" arguments during future upgrades

For searchability: remember

**Comment by Vaquero84** [comment]
Since the chocolatey.log displays the received arguments upon installation, it wouldn't be so hard to do? I just had the same idea for the ChocolateyGUI which has a export functionality for information about installed packages and having the installation arguments exported with it would enable recreating a setup. I'd very much appreciate that!

**Comment by ferventcoder** [comment]
Getting ready to pick this one up.
