### ISSUE TITLE
Is there a specification for the package format?

### ISSUE THREAD

**Issue by martensms** [chocolatey/choco#379]
Hey guys,

I'm building a cross-platform SDK which kind of solves issues for the cross-compiling or porting world of application-level code. It runs on all major operating systems as a host and therefore is something like an SDK. On Linux, it requires a proper bash environment though to not duplicate any integration logic. Required runtimes are built-in with the SDK itself, so there's no further dependencies to bundle your application to any of the supported target OS.

I wanted to switch to support the chocolatey package format, but I could not find any example packages in binary form that are reproducable. There's a chicken/egg problem where I can't afford switching to a build workflow that requires more operating systems than just one. Namely I'm currently using Docker and a minimalistic Ubuntu variant to deploy a build server and completely run the whole toolchain for Linux, OSX, Windows and all mobile platforms, because you can cross-compile from Linux to anywhere, not vice versa.

Everything is completely automated, so there's no developer being required to do anything except merging into master in the git repository and our build bots grab it up.

I tried to read the guide here in the wiki, but there's pretty much no hint what the package looks like later:
https://github.com/chocolatey/choco/wiki/CreatePackages

Is it possible to create a chocolatey package via shellscript without having chocolatey itself?

I mean, like using a plain bash script to create a `*.deb file` package without having to use the host OS nor having to use dpkg itself to create a package for the identical target OS?

Note that I'm currently trying to find help for step 1 from the following list. We chose to use this workflow, because users never want to cross-compile everything on their own if it's automatable. So users simply install the SDK with the shipped binaries of runtimes and simply have a full application deployment build for every single platform in under 10 seconds available - which is UX wise preferable and can't be changed.

1 - SDK is built from Linux to other target platforms
2 - SDK is deployed with the target platforms of 1 to download servers
3 - User installs SDK and can deploy to different set of target platforms
4 - User deploys his application to those target platforms with the SDK using binaries compiled in step 1 (e.g. Linux/arm, Linux/amd64, Linux/x86, Windows/amd64, OSX/64, Android/arm, Android/amd64, Blackberry, FirefoxOS etc.)

**Comment by ferventcoder** [comment]
@martensms 

> Is there a specification for the package format?

The packaging format is NuGet. See http://docs.nuget.org/create/nuspec-reference for the NuSpec specification. 

For the automation scripts, that is what is handled in our documentation/wiki that you have been to.

> Is it possible to create a chocolatey package via shellscript without having chocolatey itself?

Yes, well sort of. You can have the generated files part of a chocolatey packages built any way you want. They are just text files (and other binaries you want to include in the package). I'd recommend running `choco new somepackage` so you can see the boilerplate files that are necessary. Then you can take those files and build them from where ever.

To actually build the package though, you need either choco or nuget, both of which also run on Linux using Mono.

> I'm building a cross-platform SDK which kind of solves issues for the cross-compiling or porting world of application-level code. It runs on all major operating systems as a host and therefore is something like an SDK.

For packaging, I'd highly recommend you look at FPM - https://github.com/jordansissel/fpm. There is an outstanding PR to bring NuGet packaging into the fray. That is at  https://github.com/jordansissel/fpm/pull/704, but it looks like it last left off with @jordansissel asking @ringods for an update.

**Comment by ferventcoder** [comment]
Also @martensms, always best to ask questions on the gitter chat.

**Comment by ComFreek** [comment]
A Chocolatey package is nothing but a directory with the following contents (as the bare minimum):

```
|
|-- [package].nuspec
|-- tools
    |-- chocolateyinstall.ps1
    |-- chocolateyuninstall.ps1
```

The *.nuspec file is a XML file whose format is described [here](http://docs.nuget.org/docs/reference/nuspec-reference).

The chocolateyinstall.ps1 and chocolateyuninstall.ps1 files simply use one of the [helper functions](https://github.com/chocolatey/choco/wiki/HelpersReference) to automatically download, install or uninstall the software product.

Please pay attention to character encodings of the various files as noted here: [Create Packages/Character Encodings](https://github.com/chocolatey/choco/wiki/CreatePackages#character-encoding).

After creating these files, you have to package them to a *.nupkg file and push them to Chocolatey. AFAIK Chocolatey is compatible to Nuget, so that Nuget tools for Linux should do the job.

**Comment by martensms** [comment]
Thank you, guys. Very much!
I think I can go from there and know everything I need to progress :) :+1:

**Comment by ferventcoder** [comment]
@martensms There are only a few newly added items to the nuspec in the choco 0.9.9.7+ series that are not compatible with NuGet, only with Chocolatey. Keep that in mind if you feel those are necessary for what you are doing. Leave them out if you want to use NuGet to package. See https://github.com/chocolatey/choco/blob/master/CHANGELOG.md#0997-june-20-2015 and https://github.com/chocolatey/choco/issues/205 for more details.

**Comment by jpluimers** [comment]
Too bad this is closed, as Chocolatey is much more stringent about the `.nuspec` file than the [NuGet](https://en.wikipedia.org/wiki/NuGet) `.nuspec` at http://docs.nuget.org/create/nuspec-reference (which is in turn is more stringent than the [XSD](https://en.wikipedia.org/wiki/XSD) at https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd)

In addition to Chocolaty being more stringent, it also introduces `.nuspec` fields neither in the NuGet `nuspec.xsd` nor in the NuGet docs.

Likely the above has grown over time, so I think it is time to revisit the 2015 comment on just pointing to the NuGet `.nuspec` and re-open either this issue or create a new issue.

To sketch some context:

I had a hard time figuring out the exact meaning of differences between the `id` and `title` fields and the `projectUrl` and `projectSourceUrl` fields (the latter is not in the NuGet `.nuspec`).

What doesn't help here is that

- the Chocolatey documentation on rules is sparse and spread out over many places
- the rule titles are in [UPPERCASE](https://en.wikipedia.org/wiki/Uppercase), for example  [Chocolatey Software Docs | CPMR0050 - TITLE MATCHES ID (NUSPEC)](https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0050)
- even the mixed case titles in breadcrumb navigation contain wrong information, for instance "Chocolatey Software Docs | CPMR0050 - `Title` Matches `Id` (nuspec)" do not match the actual field names: these are in fact `title` and `id`
- many rule-pages are stubs as you can see from https://www.google.com/search?q=%22stub%22+site:https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules&filter=0 (which returns some 40 pages)
- one stub example (many are similar) is [Chocolatey Software Docs | CPMR0041 - PROJECTSOURCEURL MATCHES PROJECTURL (NUSPEC)](https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0041) where the title basically is the only useful information and the breadcrumb " Chocolatey Software Docs | CPMR0041 - `ProjectSourceUrl` Matches `ProjectUrl` (nuspec)" gets both `projectSourceUrl ` and `projectUrl` cased wrong.
- finding the source for the above mentioned pages on GitHub through queries like ["PROJECTSOURCEURL MATCHES PROJECTURL" site:github.com](https://www.google.com/search?q=%22PROJECTSOURCEURL+MATCHES+PROJECTURL%22+site%3Agithub.com) and [cpmr0041 site:github.com](https://www.google.com/search?q=cpmr0041+site%3Agithub.com) returned no results to create an issue for (hopefully I missed something fundamental here)

This might sound like nitpicking, maybe more so as Chocolatey is in large part maintained by volunteers, but for a project that has been around for 10+ year I kind of hoped for more documentation and specification hygiene.

Since XSD allows for both extension and restriction of data types, it would be cool if a Chocolatey `nuspec.xsd` existed that is derived from the NuGet `nuspec.xsd`.

XSD is relatively easy to parse and allows for documentation (see [`xs:annotation` - XML Schema [Book] - O'Reilly](https://www.oreilly.com/library/view/xml-schema/0596002521/re03.html), [`xs:appinfo` — Information for applications. - XML Schema [Book]](https://www.oreilly.com/library/view/xml-schema/0596002521/re06.html) and [`xs:documentation` - XML Schema [Book] - O'Reilly](https://www.oreilly.com/library/view/xml-schema/0596002521/re16.html)) which can be parsed for generation into documentation pages.

I know: XSD sounds last century, but it is all this century (and [XSD 1.1 is from 2012](https://en.wikipedia.org/wiki/XML_Schema_(W3C)#History), almost the same year that Chocolatey got started ;)

**Comment by TheCakeIsNaOH** [comment]
@jpluimers you can see the casing of each of the elements in the Chocolatey nuspec by running `choco new packageid` and looking at the resulting `.nuspec` file.

There is an open issue on the docs repository to document Chocolatey's nuspec format: https://github.com/chocolatey/docs/issues/374

> Since XSD allows for both extension and restriction of data types, it would be cool if a Chocolatey nuspec.xsd existed that is derived from the NuGet nuspec.xsd.

There technically is a xsd: https://github.com/chocolatey/nuget-chocolatey/blob/2.11_adds/src/Core/Authoring/nuspec.xsd
However, this will be superseded once the NuGet libraries are uplifted (scheduled for Chocolatey CLI v2.0.0), and as is, the code does further validation beyond the xsd format (like limiting the length of the description to 4000 characters).

**Comment by jpluimers** [comment]
@TheCakeIsNaOH thanks for digging up these links. Wish my Google Fu was better and returned them (:

Of course I know that blank packages have the correct field name casing, but my point is that the documentation should have that too.

I really wish Google had returned the proper place where these are stored on GitHub: that would make it so much easier to file issues or pull-request for them.

If you know better queries than ones like ["PROJECTSOURCEURL MATCHES PROJECTURL" site:github.com](https://www.google.com/search?q=%22PROJECTSOURCEURL+MATCHES+PROJECTURL%22+site%3Agithub.com) and [cpmr0041 site:github.com](https://www.google.com/search?q=cpmr0041+site%3Agithub.com) for that, please let me know.
