### ISSUE TITLE
Increase usage of Etags for checking consistency

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#437]
Both of what is expected to be downloaded and for whether the current download is good.

**Comment by ferventcoder** [comment]
Similar to #435.

**Comment by TheCakeIsNaOH** [comment]
I'm assuming this issue is relating to downloading files in the install script.

Relating to that, I don't think etags are useful in either validation of the download file or in validation that the server is up. 

For validating a downloaded file, it is server generated, unlike the required hardcoded checksum in the install script. So the etag is not actually useful in validating that the file is the expected file (security wise at least).

As per the RFC, there is no guarantee or standard on how the etag is generated. It could change even if the file available for download has not changed. So I don't see any value in checking that the link is still "good".
 https://www.rfc-editor.org/rfc/rfc9110.html#name-etag

**Comment by ferventcoder** [comment]
Close this. This was a thought I wanted to put down quickly back in 2015. As @TheCakeIsNaOH suggests, it is not actually consistent or useful for determining if a file is good.
