### ISSUE TITLE
Chocolatey - non-machine installed use (maybe as a NuGet package)

### ISSUE THREAD

**Issue by motowilliams** [chocolatey/choco#543]
There are situations where extra tools are needed for a software project.  This could be something as simple tail tool up to a third party server install of some dependent product.  I noticed that chocolatey had a nuget package and thought it was to solve this purpose.  A simple script or a psake task could be used to call "choco install thing-this-repo-needs".  By having choco as a nuget package and not some line item of things you need in any given repo's readme you make the zero to useful quicker.

**Comment by ferventcoder** [comment]
How is this same or different than https://github.com/chocolatey/choco/wiki/DevelopmentEnvironmentSetup?

**Comment by ferventcoder** [comment]
Right now the only issue with choco is that it may unpack files to the global install directory - I think that is only when they are not present. You can call choco something with a local choco.exe file and it should work for the most part - I'd be interested if anyone has tried this.

**Comment by gep13** [comment]
@ferventcoder this seems very similar to the use case that I was describing (when I was talking about getting Chocolatey added into Cake).  Right now, Cake relies on an installation of Chocolatey, in order to make use of the Cake Aliases that it contains.  When running on systems like AppVeyor, where Chocolatey is already installed, that isn't a problem.  However, when not running on a system like this, and you can't/not allowed to install Chocolatey, a standalone exe (similar to using NuGet.exe) would be very beneficial.  

Now you could argue that if I can use Chocolatey to install tools onto the machine in question, why can't I get Chocolatey installed, and that is a good question :smile:   For now, for things like ChocolateyGUI, I install Chocolatey as part of the build process:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/BuildScripts/default.ps1#L249

That just adds time to the build, so it is definitely possible to go down that route.  But I think we should support both.  @motowilliams hopefully I haven't picked you up wrong.  Sounds like we are talking about the same thing.

**Comment by motowilliams** [comment]
I'll spell out my current use case for this.  I have a .NET repo for a training course.  Part of the course is code training but also some infrastructure stuff as well.  CI and CD so we're creating some scripts to install TeamCity and Octopus Deploy (and some other tools) locally on the students machine.  If my day-1 setup script could rely on choco being there as part of a nuget restore call and then choco install mystuff then I make that flow a lot better.

**Comment by jozefizso** [comment]
We install the `chocolatey` package from nuget.org. We can run `choco.exe pack` at it creates the cocholatey package, but choco.exe will echo non-important error messages. It would be great to get rid of those error messages.

```
choco.exe pack agent.nuspec --version 6.0.0
Error serializing type chocolatey.infrastructure.app.configuration.ConfigFileSettings:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Error updating 'C:\ProgramData\chocolatey\config\chocolatey.config'. Please ensure you have permissions to do so:
 Access to the path 'C:\ProgramData\chocolatey\config\chocolatey.config' is denied.
Chocolatey v0.9.9.8
Attempting to build package from 'agent.nuspec'.
Successfully created package 'agent.6.0.0.nupkg'
```

**Comment by jozefizso** [comment]
The serialization error is happening because the locally installed chocolatey is in different version the the one installed as NuGet package. Therefore it tries to overwrite the `chocolatey.config` file.

**Comment by ferventcoder** [comment]
@jozefizso that nuget package is the same as the one on Chocolatey - why not just call `nuget install chocolatey -Source https://chocolatey.org/api/v2`?

Side note - I should probably update the one on nuget or remove it.

**Comment by jozefizso** [comment]
@ferventcoder we use only our internal NuGet Gallery and public NuGet.org as package sources when installing packages required to build our project.

We may install it from Chocolatey.org as well.

**Comment by pauby** [comment]
This is an old issue with no updates since 2016. We now have an MSI that could solve this problem.

I'm going to go ahead and close this, but we can reopen it if necessary.
