### ISSUE TITLE
Push to dot org may send empty packages

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#575]
See https://chocolatey.org/packages/orvibos20cli/1.0 (review comments - only visible to mods or maintainers once the package is approved).

> ferventcoder (reviewer) on 24 Jan 2016 06:23:02 +00:00:
> 
> There are no files in this package now. Was that intentional?
> 
> LeonV (maintainer) on 24 Jan 2016 08:18:36 +00:00:
> 
> No, the only difference to the one uploaded previously is description. However, I did 'choco push' instead of upload via website. I'll retry uploading via website.

@Leon99 let's follow up here with what I requested.

**Comment by ferventcoder** [comment]
Also from the comments:

I would like to attempt to reproduce this issue. What version of choco were you using? Can you provide the log output? It should be somewhere in your `%ChocolateyInstall%\logs` folder in one of the files. I am curious if this was just a fluke or it is an issue with choco that we need to resolve?

**Comment by Leon99** [comment]
I'm using Chocolatey v0.9.9.11. I simply ran 'choco push' from the package directory. I've just repeated it with rdpwrapper.
Unfortunately, I didn't find any logs for that push under %ChocolateyInstall%\logs.

**Comment by ferventcoder** [comment]
FWIW, I am not running into the same issues. What are all the steps you took to prepare and push the file?

Also, if you are not seeing it in the log file, you are probably not using the one with 0.9.9.11.

Run `where.exe cpush` and `where.exe choco` to validate the commands are coming from the appropriate locations. Also run `choco push --shimgen-log` for me and provide that output.

**Comment by Leon99** [comment]
C:\WINDOWS\system32>where choco
C:\ProgramData\chocolatey\bin\choco.exe

C:\WINDOWS\system32>where cpush
C:\ProgramData\chocolatey\bin\cpush.exe

C:\Users\Leon\Documents\Visual Studio 2015\Projects\Anroo\Anroo.OrviboS20.Cli.Choco\bin\Release>choco push --shimgen-log
[shim]: Set up Shim to run with the following parameters:
  path to executable: C:\ProgramData\chocolatey\choco.exe
  working directory: C:\Users\Leon\Documents\Visual Studio 2015\Projects\Anroo\Anroo.OrviboS20.Cli.Choco\bin\Release
  is gui? False
  wait for exit? True
  command (optional):
[shim]: Command line 'choco  push --shimgen-log'
[shim]: Current process '"C:\ProgramData\chocolatey\bin\choco.exe"'
[shim]: Command line after removing process 'choco  push --shimgen-log'
[shim]: Shifting off the first argument since process didn't catch it
[shim]: Arguments after removing shimgen args - 'push'
[shim]: Arguments are 'push'
[shim]: Calling 'C:\ProgramData\chocolatey\choco.exe push'
Attempting to push orvibos20cli.1.0.nupkg to https://chocolatey.org/
Failed to process request. 'A package with id 'orvibos20cli' and version '1.0' already exists and cannot be modified.'.
The remote server returned an error: (409) Conflict..
[shim]: Exiting with '1'.

**Comment by gep13** [comment]
>@Leon99 said...
Failed to process request. 'A package with id 'orvibos20cli' and version '1.0' already exists and cannot be modified.'.
The remote server returned an error: (409) Conflict..

Since the 1.0 package version has been approved, and therefore published, you will no longer be able to push a package with the same version, since package versions are immutable, once approved.

**Comment by ferventcoder** [comment]
@Leon99 everything there looks appropriate.

**Comment by TheCakeIsNaOH** [comment]
@Leon99 (or anyone else following this issue) are you still seeing this issue?
