### ISSUE TITLE
choco pack doesn't include chocolatey-specific metadata

### ISSUE THREAD

**Issue by bdukes** [chocolatey/choco#607]
I believe this started yesterday when I installed the pre-release version of `chocolatey` and `choco.extension` package.  I currently have version 0.9.10-beta1-116-ga1474ea installed.

I updated the [nuspec for hg](https://github.com/bdukes/Chocolatey-Packages/blob/ee4558828225f0f1650649999918f89602cea55a/hg/hg.nuspec), adding `docsUrl`, `mailingListUrl`, `bugTrackerUrl`, and `releaseNotes` (and already had `packageSourceUrl` specified).  However, when I submitted the package, the review indicated I still needed to add those elements.  When I review the nupkg that is produced from `cpack` (or `choco pack`), I see that the nuspec doesn't include any of those new elements, except `releaseNotes`.

**Comment by bdukes** [comment]
The version of `nuget` available on my path is 3.3.0.212, if that matters.

**Comment by ferventcoder** [comment]
@bdukes Chocolatey doesn't use nuget.exe for packing. It uses a built-in Nuget.Core.dll.

**Comment by ferventcoder** [comment]
Ah NuGet... :/

**Comment by ferventcoder** [comment]
This is fixed and will go out in a beta today.

**Comment by ferventcoder** [comment]
A beta just got pushed with these fixes. https://chocolatey.org/packages/chocolatey/0.9.10-beta-20160204
You can install it immediately if you use `-version` in the switches, otherwise it will be available in about an hour with the `-pre` switch.

`choco upgrade chocolatey -version 0.9.10-beta-20160204`

Would love some verification that this works.
