### ISSUE TITLE
my PC doesn't have powershell to install files

### ISSUE THREAD

**Issue by Arburator** [chocolatey/choco#635]

**Comment by gep13** [comment]
@Arburator what Operating System are you running?

Chocolatey pretty much requires PowerShell in order to function.  Almost all of the installation packages contain PowerShell scripts to aid with the automatic installation of the packages.  So you are going to need to have at least version 2 of PowerShell installed in order to use Chocolatey.

**Comment by Arburator** [comment]
I am running windows Vista as thats the required build model for my PC, I couldn't give you its version as control panel is broken.

**Comment by ferventcoder** [comment]
Our documentation lists PowerShell v2+ as a requirement, the same for .NET Framework 4. I'm going to need to close this as invalid. Thanks!
