### ISSUE TITLE
Spelling error in "{packagename} has been upgradeed successfully."

### ISSUE THREAD

**Issue by kendaleiv** [chocolatey/choco#64]
"skype has been upgradeed successfully." was output with chocolatey v0.9.9-rc1.

**Comment by gep13** [comment]
ah! The issue is here:

https://github.com/chocolatey/choco/blob/master/src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs#L209

The concatenation of `upgrade` and `ed` results in what you are seeing here.  I can think of a couple hacks to make this work, but I will wait and get input from @ferventcoder before making any changes to the codebase.

Thanks for reporting this!

**Comment by christianrondeau** [comment]
Hoping this will be fixed before 1.0... It makes chocolatey look unprofessional, and in the case of a package manager, trust and impressions are important :)

**Comment by ferventcoder** [comment]
Fixed in https://github.com/chocolatey/choco/commit/91dc3f94e441bf94ab5a130005c0cc2d180a96ec to be out with 0.9.9.5
