### ISSUE TITLE
RefreshEnv (Refresh Environment Variables) Should also work in PowerShell

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#664]
cmd.exe has long had a nice command to run to update environment variables without needing to close the shell: `refreshenv`. Bring that functionality to PowerShell.exe as well.

**Comment by masaeedu** [comment]
@ferventcoder How do we use this? I've installed 0.9.10.3 and I can still only see Refreshenv.cmd, no Refreshenv.ps1.

**Comment by ferventcoder** [comment]
It's not the name of the file. You are running a function alias that has been added to PowerShell through your profile.

**Comment by ferventcoder** [comment]
Have you tried running the function?

**Comment by ferventcoder** [comment]
Sorry, was responding from the email and didn't see that you added more here. From the install of choco, it would have added to the profile of the installing user. Then you need to run `. $profile` as the instructions state during the install of choco or close and reopen powershell.

**Comment by ferventcoder** [comment]
If it isn't in your profile, you will need to add the module to it. We are worki g on a troubleshooting doc for this

**Comment by masaeedu** [comment]
@ferventcoder Ah, yes, I noticed that message but I didn't have a chance to react because it was part of a script. It works if I add a line to source my profile, thanks!

**Comment by ihor-drachuk** [comment]
Currently it doesn't work in PS

**Comment by TheCakeIsNaOH** [comment]
@ihor-drachuk `refreshenv` does work in powershell, but it requires the `chocolateyProfile` module (which also has tab completion) to be enabled.
Here is a guide with more information: https://www.youtube.com/watch?v=jdZrigvxwws

**Comment by ihor-drachuk** [comment]
In common, it would be fine if it could work without such unobvious dependencies. Or if dependencies are installed with the tool, which is installed, but currently doesn't work without them. Or if tool failed to do it's work, then let it notify somehow about failure and suggest that there are some missing component and there are some solution.

@TheCakeIsNaOH Thank you for information, I'll try.

**Comment by corbob** [comment]
@ihor-drachuk generally if you have a PowerShell Profile it will add the code to import the `chocolateyProfile`, however there are a number of reasons the `chocolateyProfile` isn't added automatically:

1. If there is no PowerShell profile, we will not create one as there are a number of scenarios where this would result in further issues. By default on Windows the Execution Policy is undefined and in many cases will be treated as `AllSigned` which means us adding a PowerShell profile will result in an error every time someone loads PowerShell.
2. If there is a PowerShell profile, but it is signed, we will not update the profile because we didn't sign it and doing so would break the profile script.

As for being unobvious, Chocolatey does alert you to this during the install process (to be fair this just says tab completion, and not a word about refreshenv):
![image](https://user-images.githubusercontent.com/30301021/147173314-f5a5e7d5-84c8-4e66-9c8f-f7187a1124e0.png)

**Comment by ihor-drachuk** [comment]
@corbob Thanks for the answer. Exactly! I'm expecting working just `refreshenv` in PS. Especially if it finishes with zero status code. And it's not obvious that it's somehow connected with tab completion or profiles or that it could be broken because of them or smth similar.
