### ISSUE TITLE
choco ls command - list information about an installed package

### ISSUE THREAD

**Issue by drusellers** [chocolatey/choco#681]
I would like a feature similar to `brew ls <packageName>` as mentioned in #644 

Depends on #690.

**Comment by ferventcoder** [comment]
Choco list pkgname already exists - with a different purpose. Perhaps choco ls <pkgname>?

**Comment by drusellers** [comment]
If `list` exists and most think of `ls` as an alias, than maybe something like `choco files <packageName>` The specific issue I ran into was installing a powershell thing and then I had no idea where to go look for it. So anything that can help with that experience would be awesome.

**Comment by alexchandel** [comment]
`choco ls` is a cool idea for listing the files, and it parallels the standard unix `ls` command.

It's worth noting that `brew list` (and its alias `brew ls`) actually has two functions. With no arguments it lists the installed packages, but with an argument (e.g. `brew list wine` or `brew ls wine`) it lists the files of that packages. Not that that's necessarily the best way to do it, that that it isn't.

**Comment by Lemmingh** [comment]
Hi, @alexchandel

> `choco ls` is a cool idea for listing the files, and it parallels the standard unix `ls` command.

No, it is **NOT cool** at all.

---

There are a great number of ways to **degrade end users' experience**.
For CLI, they include but are not limited to

* Introducing many aliases for the same thing
* Using different naming styles and syntax conventions between commands
* Using complex syntax
* Requiring user to know the internal (*It occurs usually when a program requires user to provide how to do instead of what to do.*)
* Providing unclear guides and instructions

---

It's obvious that [the commands of `choco`](https://chocolatey.org/docs/commands-reference) are formed by **human readable English words**, and most of the words are in their base form. Only few aliases break the rule by using plural noun so far.

The `ls` does **NOT** parallel the command naming convention of `choco`. It will lead to confusion if it appears.

Besides, for most users, Chocolatey is just [a utility to help them setup computer](https://chocolatey.org/docs/why).
Many users of Chocolatey are average user of Windows PC.
Even if you are an IT pro, it is still **NOT a good idea** to spend time in distinguishing between commands and then choose your preferred one — It is a waste of energy.

Additionally, on the one hand, a word such as `ls` is awfully **meaningless** to those who have little knowledge of Unix.
On the other hand, for those who are familiar with Unix, `ls` is quite similar to `list`, but they are intended to do different things in `choco`.
Again, it will lead to **confusion** if it appears, just like [what **drusellers** said](https://github.com/chocolatey/choco/issues/681#issuecomment-207434603)

> If `list` exists and most think of `ls` as an alias, then ...

**Conclusion**:
`choco ls` is a **bad** idea. We'd better use another name.

---

Now, let's go back to the original topic of this issue.

**This issue** is about a way to **get install location (and perhaps file list) of a package in `choco`**.

> Besides, there are related issues in **ChocolateyGUI**:
>
> * chocolatey/ChocolateyGUI#278 for adding installation path column of installed packages in list view of Chocolatey GUI
> * chocolatey/ChocolateyGUI#597 for displaying install location in the package details page of Chocolatey GUI

In my opinion, the command `choco file <packageName>` proposed by **drusellers** is a nice place to display this info.

It can also be added to the output of `choco info <packageName> --local-only`, which was added in 0.9.10.0, if it's possible.

**Comment by pauby** [comment]
We don't have any plans to add `ls` as an alias for `list`.

I'm going to go ahead and close this, but we can reopen it if necessary.

**Comment by epa** [comment]
Hi @pauby , thank you for looking at this issue.  But I fear you might have misunderstood what it is about.  You say, "We don't have any plans to add `ls` as an alias for `list`."  But that's not what is being requested here.  Rather, what a few people have asked for is a way to list the files (or at least the install directory) of a given Chocolatey package once it has been installed.

On other packaging systems this is a common operation, for example `rpm -ql bash` will list the files in the bash package installed on the system.  For Chocolatey this could be `choco ls firefox` or whatever.  It would not be the same as the existing `list` command.  The exact name used doesn't much matter, I think.

**Comment by pauby** [comment]
To find the files in the package you could either open it or visit the package page if it's on the Chocolatey Community Repository.

To find the installation directory, I believe there are other issues requesting this. From memory this would come through the `info` command.

Neither of them need a separate command.
