### ISSUE TITLE
When removing meta/virtual, if a .install or .portable is also found, report how to remove

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#735]
This is nearly the same as @dtgm does in his packages:

~~~powershell
# powershell v2 compatibility
$psVer = $PSVersionTable.PSVersion.Major
if ($psver -ge 3) {
  function Get-ChildItemDir {Get-ChildItem -Directory $args}
} else {
  function Get-ChildItemDir {Get-ChildItem $args}
}
# MetaPackage
$warningPreference = "Continue"
$chocoLib = Join-Path $env:ChocolateyInstall "lib"
if (Test-Path -PathType Container (Join-Path $chocoLib 'systemninja.*')) {
  Write-Warning "Uninstall NOT complete."
  Write-Host
@"
  This package is a metapackage; a chocolatey feature not yet fully implemented.
  To retain future compatibility this package does not uninstall the dependent
  package it points to as designated with *.install or *.portable.`n
"@
  Write-Warning "To finish removing the program installed by package systemninja, please also run the command:"
  $text += " `n`tchoco uninstall "
  $list = (Get-ChildItemDir $chocoLib\systemninja.*).Name
  foreach ($i in $list) {
    $text += "$i "
  }
  $text += "-y`n"
  Write-Host $text
}
~~~

The message we would add is the following:

~~~sh
WARNING: Uninstall NOT complete. You have removed a metapackage that 
 has a *.install/*.portable that it installed (this package represents 
 discoverability).

Would you like to uninstall ____ package as well? ([Y]es/[N]o) 
~~~

The prompt would timeout after 30 seconds with a default value of no.  If no, provide the following text:

~~~sh
WARNING: To finish removing ___, please also run the command: `choco uninstall _____`
~~~

**Comment by ferventcoder** [comment]
@dtgm - by the way, meta packages are fully implemented and have been since day 1 of NuGet. It's virtual packages that are not fully implemented.

**Comment by dtgm** [comment]
You're right, when I stated `This package is a metapackage; a chocolatey feature not yet fully implemented.` I was thinking in my head the unique use case of metapackages that are to designate install type by install/portable which is why I like your message better because it highlights that differentiation, `You have removed a metapackage that has a *.install/*.portable that it installed`

It is also important to have this message since trying to uninstall the `foo.install` first says you actually, you have to uninstall `foo` and I don't think it is clear to the user they have to uninstall both packages separately, and in the correct order.

 `cinst rufus -y`
which installs `rufus.install` as a dependency
```
cuninst rufus.install -y
Uninstalling the following packages:
rufus.install
rufus.install not uninstalled. An error occurred during uninstall:
 Unable to uninstall 'rufus.install 2.8' because 'rufus 2.8' depends on it.

Chocolatey uninstalled 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - rufus.install
```
and then `cuninst rufus -y` is silent about the status of the actual package that uninstalls the program which brings us to the problem being addressed in this issue.

**Comment by ferventcoder** [comment]
Looks pretty good. Also puts out the first warning message with ANY install, upgrade or uninstall for packages that are in warning.

**Comment by ferventcoder** [comment]
That probably closes another ticket (related to noting pins).
