### ISSUE TITLE
Create custom templates

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/choco#76]
I would like to be able to modify templates. My packages all look sort of similar so I find it faster to actually copy an existing package and modify it. If I could create a custom template the new-function would actually be useful to me.

**Comment by rismoney** [comment]
Something like warmup?
https://chocolatey.org/packages/warmup

**Comment by aronovgj** [comment]
i know warmup and it was fine for me to use a 3rd party solution because the old chocolatey did not offer this at all. but if chocolatey wants to offer templates it should also offer a way to modify them. i mean `new` is supposed to eliminate the need to use warmup, right?

**Comment by ferventcoder** [comment]
If you drop a template into `$env:ChocolateyInstall\templates` folder, you can use `-t name_of_template` to generate a choco template based on that. So for:

![image](https://cloud.githubusercontent.com/assets/63502/9952997/0603b334-5da2-11e5-8b6d-65a5dbf5d8e0.png)

You would call `choco new pkgname -t organization` and choco will use the template folder instead of the built-in template.

To replace the built-in template, you should put a folder in the template with the name of "default". Then choco will use that instead of the built-in template with no need to specify a template name.

**Comment by ferventcoder** [comment]
@KosherSalt This is done and will go out in choco 0.9.9.9.

**Comment by ferventcoder** [comment]
~~~xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Do not remove this test for UTF-8: if ԏԠdoesnӴ appear as greek uppercase omega letter enclosed in quotation marks, you should use an editor that supports UTF-8, not this one. -->
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>[[PackageNameLower]]</id>
    <title>[[PackageName]] (Install)</title>
    <version>[[PackageVersion]]</version>
    <authors>Original authors</authors>
    <owners>[[MaintainerName]]</owners>
    <description>__REPLACE__MarkDown_Okay [[AutomaticPackageNotesNuspec]]
    </description>
    <tags>[[PackageNameLower]] admin</tags>
    <!--<dependencies>
      <dependency id="" version="__VERSION__" />
      <dependency id="" />
    </dependencies>-->
  </metadata>
  <files>
    <file src="tools\**" target="tools" />
  </files>
</package>
~~~

**Comment by ferventcoder** [comment]
You can get the names by running `choco new -h`:

~~~
Possible properties to pass:
    packageversion
    maintainername
    maintainerrepo
    installertype
    url
    url64
    silentargs
~~~

However `PackageName` and `PackageNameLower` also show up as they are based on the name of the package that you pass e.g. "bob" in `choco new bob`

**Comment by ferventcoder** [comment]
Documentation coming up at https://github.com/chocolatey/choco/wiki/How-To-Create-Custom-Package-Templates
