### ISSUE TITLE
[WikiPageRequest] Please add a "Troubleshooting" page to the Wiki

### ISSUE THREAD

**Issue by KurtPfeifle** [chocolatey/choco#768]
I'd like to see a "Troubleshooting" page in the Wiki.

It should give some general troubleshooting hints and explain what the minimal pre-conditions are to successfully use Chocolatey and its most important `choco` commands.

Of course, some of the questions arising around `choco` are more general PowerShell questions. However, a **_lot**_ of users will get into contact with PowerShell for the first time because of `choco`, so these general PS topics should not be excluded!

Here are a few examples which could be covered for a start:
1. Can I use `choco` in a `cmd.exe`-Shell too? If so, are all the `choco` subcommands expected to work equally well (given that I'm an Administrator)? If not, why? Which ones are expected to fail?
2. Do I need to be an Administrator for most commands which change something? Which commands do require elevated privileges and which don't?
3. Why does **_`choco in<tab><tab>`**_ not work for me? Which _`Import-Module`_-command has to be run in order to fix non-working tab completion? How can I check which modules are imported into my current PoSh environment? Should I import these modules permanently into all my choco/PoSh sessions? How do I do this?
4. **_`alias dir`**_ tells me that **_`dir`**_ is the same(?) as **_`Get-ChildItem`**_. However, the command **`dir \\some\unc-path`** does work, whereas **`Get-ChildItem \\some\unc-path`** does not.
5. I'm seeing error message code **_`1618`**_. What does it mean? I've also seen other numbered message codes in the past. Is there a list of all these codes and their meanings to look up?
6. [...to be amended...]

**Comment by ferventcoder** [comment]
@KurtPfeifle I'm going to add some answers here until we have the page up - I think you probably already know the answers for most of these.

> Can I use choco in a cmd.exe-Shell too? If so, are all the choco subcommands expected to work equally well (given that I'm an Administrator)? If not, why? Which ones are expected to fail?

Yes, choco is actually a command line tool `choco.exe`. The only benefit you do not get is the tab completion that you get in PowerShell.

> Do I need to be an Administrator for most commands which change something? Which commands do require elevated privileges and which don't?

We probably need to have these better organized. This is a great question! 

The answer for most of this is it depends. 👍  (spoken like a true software developer I know, ;) )
The packages themselves dictate what they require as far as administrative privileges in most cases. So if you are performing install/upgrade/uninstall, Chocolatey currently doesn't do anything differently than what the system would require be done - usually admin privileges are required.

> Why does choco in<tab><tab> not work for me? Which Import-Module-command has to be run in order to fix non-working tab completion? How can I check which modules are imported into my current PoSh environment? Should I import these modules permanently into all my choco/PoSh sessions? How do I do this?

This means the import failed during install/upgrade. Chocolatey does supply a warning when this happens in the install/upgrade log. Take a look there.

 * If this is the same shell that the upgrade occurred in, the message states you need to update your profile - run `. $profile`. Try that first, then try restarting your shell and see if it takes hold.
 * If it still doesn't work, it means there was a failure setting the profile with the module.
 * This could be due to PowerShell Execution Policy settings. Run `Get-ExecutionPolicy` - if it is set to `Restricted` you need to adjust that to something like `RemoteSigned`. See about execution policies (link)
 * If that is fine, then we need to look at your "$profile". Run `type $profile`. Examine the output. You should have something like this in the file:

~~~powershell
# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
~~~

 * If you don't see that, let's add it. Run `Write-Host $profile` - note the location and open it up in an editor (anything but plain old notepad.exe for the love of..., well your favorite editor).
* Now let's add that text above to the profile. Save and close the file. Now type `. $profile` to update your current Shell. Give `choco in<tab>` a shot again. If it still doesn't work we'll need to examine something a bit more deeply about your environment. Please submit an issue so we can investigate.

> alias dir tells me that dir is the same(?) as Get-ChildItem. However, the command dir \\some\unc-path does work, whereas Get-ChildItem \\some\unc-path does not.

General PowerShell help here? I'm guessing dir is not just an alias, that it does a bit more like telling get-childitem this is for a directory.

**Comment by ferventcoder** [comment]
Add https://groups.google.com/d/msgid/chocolatey/58ef0ece-5e2a-4c2c-82a8-10e1711bdd3f%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by ferventcoder** [comment]
Done. See https://github.com/chocolatey/choco/wiki/Troubleshooting
