### ISSUE TITLE
Send parameters to install script - feature 

### ISSUE THREAD

**Issue by GitAMBS** [chocolatey/choco#792]
Have plenty of scenarios where I would have loved to be able to send parameters to the install script through choc.exe install. 
That would grant a lot of flexibility in regard to possible configurations upon deployment. 

Eg. With Java it could be awesome to be able to use the same package with or without auto update enabled from the same package.

**Comment by ferventcoder** [comment]
You can do this now - use package parameters https://chocolatey.org/docs/how-to-parse-package-parameters-argument

**Comment by ferventcoder** [comment]
Are you looking for something different?

**Comment by GitAMBS** [comment]
Forgot about this issue - Sorry. 

No that were exactly what i was looking for. 

The community extension do make this a lot easier. Yet the parsing parameters is (still) tricky at best.
Have not been able to get arguments with spaces to actually parse in to the install script properly.
been through the docs - several times today and tried all thinkable combinations of " and '.
" are still stripped before they are added to the $packageparams variable (via powershell). Causing the get-packageparameters function to split at the space. 

But that is for another issue.

Buttom line, still feels like this should be easier.

**Comment by ferventcoder** [comment]
@GitAMBS Agreed it should be easier - you are dealing with PowerShell.exe and cmd.exe and their behavior. That's why we explicitly document the only known way to have this work at `choco -?` and https://chocolatey.org/docs/commands-reference#how-to-pass-options-switches - that is `--params="'/ITEM:value /ITEM2:value'"`: 

* **Quote Values:** When you need to quote an entire argument, such as
when using spaces, please use a combination of double quotes and
apostrophes ("'value'"). In cmd.exe you can just use double quotes
("value") but in powershell.exe you should use backticks
(`` `"value`" ``) or apostrophes ('value'). Using the combination
allows for both shells to work without issue, except for when the next
section applies.
* **Pass quotes in arguments:** When you need to pass quoted values to
to something like a native installer, you are in for a world of fun. In
*cmd.exe* you must pass it like this: `-ia "/yo=""Spaces spaces"""`. In
*PowerShell.exe*, you must pass it like this: `-ia '/yo=""Spaces spaces""'`.
No other combination will work. In PowerShell.exe if you are on version
v3+, you can try `--%` before `-ia` to just pass the args through as is,
which means it should not require any special workarounds.
