### ISSUE TITLE
Use Remembered Arguments for a Package During Upgrades

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#797]
Following #358 (and related to #357), we capture the arguments passed during install/upgrade. Now we need to pass them to the upgrades automatically.

cc @seankilleen

### Notes
This is in preview in 0.10.4 and will be turned to 'on' automatically in a future release. We are goign to be continually making it better and won't turn it on by default until it is ready. If you want to turn it on and start using it, once you have 0.10.4 installed, run
`choco feature enable -n useRememberedArgumentsForUpgrades`.

You can also do this per command with `--use-remembered-arguments`. You can also turn it off per command with `--ignore-remembered-arguments`.

A couple of important notes:
* Remembered arguments would be from the last version, so if you upgraded, those original install arguments did not carry up the chain unless you passed them at the command line during upgrade. There is probably a manual way to go and get those and put them in the latest version. This is expected.
* [Security] The `.arguments` file where these are stored will be completely encrypted from now on. This is a security mechanism in case there is any sensitive data being passed on the command line. This is by design.
* This is not yet capturing arguments that only apply to the licensed editions of Chocolatey, but we expect to capture that in the future. This will be handled in a future release.
* If you passed along a password for install in versions less than 0.10.4, it encrypted only that value and this will not unencrypt that (so it will be passed incorrectly). If this was a working feature in the past, this would be a breaking change. There is a workaround - you can override the value it picks up by passing the new password on the command line with the upgrade command. This is not the best thing, but since we have a workaround, we probably won't move forward with a fix for this (that is unless someone else really feels strongly about this and files an issue + provides a fix with specs).
* This is not, and likely will never be, able to remember and pass through a custom source used for installation. Those are set very, very early in the process. This is open for discussion, but the workaround is to ensure your default sources contain everything you need.
* Currently the saved values will override what is passed on the command line for the values it overrides. This is sub-optimal. However it is tricky. We'll post an issue that will resolve that in a future release. If you need to ignore those arguments passed through, be sure to pass `--ignore-remembered-arguments` to the upgrade command. This will be fixed in a future release.

**Comment by dragon788** [comment]
Could the original parameters also be made accessible via a custom Chocolatey function for use in the chocolateybeforemodify and chocolateyuninstall scripts? Get-ChocolateyPackageParameters or something.

In the future the ability to specify an arbitrary package name to query so that if I wanted to install a plugin for an application that was installed with a custom path, the plugin is able to "find" the application? This could potentially be a security issue if packages are modifying other packages willy nilly.

https://gitter.im/chocolatey/choco?at=581b7fcce462097a3004a1e6

**Comment by majkinetor** [comment]
I see that parameters are stored in `.chocolatey`, I could create this in chocolatey-core extension. Currently we have [Get-PackageParameters](https://github.com/chocolatey/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/extensions/Get-PackageParameters.ps1) and I could update it with new option `TryInstall` that returns original install parameter if user is updating. 

Now i am not sure how to know if package is being updated or installed from within installer (@ferventcoder?), or I can simply use this as a surogate:

```powershell
function IsUpgrading($PackageName = $Env:ChocolateyPackageName) {
    $pkg = (choco list -ler $PackageName | select -Last 1) -like "$PackageName*"
    if (!$pkg) { return $false }

    $version = $pkg -split '\|' | select -Last 1
    if ([version]$version -lt [version]$env:ChocolateyPackageVersion) { return $true }
    $false
}
```

I am also not sure what happens with multiple installations of the same package but I guess any eventual issue here shouldn't be show stopper because this features is used by few.

**Comment by majkinetor** [comment]
Actually, I can use `beforeModify` to know if its update.

**Comment by ferventcoder** [comment]
@majkinetor accessing the `.chocolatey` is a huge anti-pattern and will be viewed as hostile. Consider the `.chocolatey` directory as private data for Chocolatey only. If it was meant to be accessed it would not be a hidden folder starting with a `.`.

This is set to be implemented in the upcoming version of Chocolatey, if you are up for helping with that, great.

**Comment by ivanatpr** [comment]
When this is implemented, there should also be some easy way of exposing the current remembered arguments to the user. Personally I'd prefer if it was made part of the regular non-verbose output of `list -l` and `upgrade -noop`

Instead of:
>You have jre8 v8.0.45 installed. Version 8.0.121 is available based on your source(s).

You could have something like:
>You have jre8 v8.0.45 (-x86) installed. Version 8.0.121 is available based on your source(s).

**Comment by ferventcoder** [comment]
@ivanatpr may not be a bad idea to go ahead and file a followup ticket for that as it likely won't be handled for this upcoming release.

**Comment by ferventcoder** [comment]
@ivanatpr were you going to create a follow up ticket for that?

**Comment by ferventcoder** [comment]
Okay, this is going into 0.10.4, but as an opt in while we work out additional kinks.

Also, from now on the entire set of values in the arguments will be encrypted.

**Comment by ferventcoder** [comment]
I will update the issue at the top to explain how to turn it on.

**Comment by ferventcoder** [comment]
Issue updated with all of the current known issues and information. If you are interested in this feature, I suggest reading over the notes.

**Comment by aaccioly** [comment]
Hi @ferventcoder, is this enabled by default now or do I still need to run `choco feature enable -n useRememberedArgumentsForUpgrades` manually to enable it for all packages?

**Comment by ferventcoder** [comment]
@aaccioly not enabled by default. You can always check with `choco feature list`. Also subscribe to [chocolatey-announce](https://groups.google.com/group/chocolatey-announce) so you will get a notice when it is turned on by default.

**Comment by ferventcoder** [comment]
Keep in mind there is a known issue and reproing it or determining the cause is quite difficult - https://github.com/chocolatey/choco/issues/1443

**Comment by bcurran3** [comment]
This needs to be re-opened.
REF: https://github.com/chocolatey/choco/issues/1547

**Comment by CollinChaffin** [comment]
This need to be reopened.  Latest versions for some time now actually if you perform a `choco upgrade -y ALL` what happens on mult machines I can reproduce easily is that if ONE single package in that list had specific install arguments to remember on upgrade, that arg is literally being passed FOREVER to EVERY single MSI as even the logs show.  In my case, Notepadplusplus install was installed with this arg:  `cinst --pre -y notepadplusplus.install -ia '/allowAppDataPluginsLoading=true'` and now every package upgrade forever on this machine runs this and here is an error I just got from a MSI that actually does NOT simply ignore the switch unknown to it:

````
ERROR: Running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\p
andoc\tools\pandoc-2.4-windows-i386.msi" /quiet /allowAppDataPluginsLoading=true] was
 not successful. Exit code was '1639'. Exit code indicates the following: The command
......Truncated
````

Note the NotepadPlusPlus MSI switch being passed to `Pandoc` which obviously does not nor ever has used that switch unique only to NPP, and the main chocolatey log also even shows all the successful upgrades which also wind up getting passed this switch from a single package remembered args.  If this occurs with a switch that IS actually used by other packages, it will be catastrophic.

**Comment by CollinChaffin** [comment]
@bcurran3 @ferventcoder Hey guys can this be re-opened please?  See my comment above and let me know if this is already a fix underway or whether you need additional details above what I already posted.  Thanks!

**Comment by ferventcoder** [comment]
We don't reopen something that has been completed. You are seeing a bug with it, which means a new issue. This is by the way corrected in the beta.

**Comment by ferventcoder** [comment]
@CollinChaffin https://github.com/chocolatey/choco/commit/347f09f2f53465aca82a3c7fab2a08c28ea829eb

**Comment by CollinChaffin** [comment]
@ferventcoder Then why with today's beta is it STILL adding old remembered arguments from a single package I installed over a year ago?  Where are remembered arguments stored so I can clear this out and if what you are saying is correct I'm still not clear why I need to do so.

**Comment by CollinChaffin** [comment]
@ferventcoder I just realized this is exactly what you called a MAJOR BUG in issue #1443 - same issue.  400 package upgrades will carry a single argument (like the mentioned 32/64 bit snafoo when NPP arg was carried to VLC and other packages).  In my case, I can show a log with today's beta applying a switch of `'ADD_CMAKE_TO_PATH=System'` (a switch that obviously applies only to CMAKE) over and over with a `cup ALL` which on top of just looking silly, is actually causing damage when packages that vomit on that unknown switch enough that they simply fail to upgrade.

It looks like issue #1443 is still at least listed as OPEN and at some point someone understood the severity and I know everyone is busy but your comments that it was a major bug in that issue were made over a year ago, and so I was bringing it up again because it's still not fixed and is in fact severe.  Let me know if there is anything else I can test to help.

**Comment by ppvnf** [comment]
is this gonna be enabled by default or the idea was dropped out?

**Comment by TheCakeIsNaOH** [comment]
@ppvnf it still is expected to be enabled by default at some point, but there are still open issues with this feature, specifically #2886 and #2761

Likely it would not be enabled until after there is at least one release with no known or found issues with it.

**Comment by ppvnf** [comment]
That makes sense. Thank you

**Comment by pauby** [comment]
@gabriel-vanca This issue was closed as completed in 2017. If you're looking for an update on [this comment](https://github.com/chocolatey/choco/issues/797#issuecomment-1515496821), then this has not been abled by default and there are no immediate plans to do so. We will look at it again during the next release cycle.
