### ISSUE TITLE
Choco with unknown command should show help menu

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/choco#938]
### What You Are Seeing?

`choco hi` outputs - Could not find a command registered that meets 'hi'

### What is Expected?

I should see the help menu

**Comment by TeaDrivenDev** [comment]
Thanks for picking this up!

Preferably, I think, it should just show the "Commands" part here and then say something like "Type 'choco /?' for full help". It's supposed to give you a first idea of what you might want to do, so it shouldn't be too much information at once. The full help will almost certainly scroll a page or two in most console windows, and that can be a bit disorienting (I know it is for me).

What about `choco` without any (attempted) command? I think that should also at least tell you about the `/?` switch, because while it's the Microsoft command line standard, it's not the most intuitive thing to think of if you don't happen to *know* that.

**Comment by ferventcoder** [comment]
> What about choco without any (attempted) command? I think that should also at least tell you about the /? switch, because while it's the Microsoft command line standard, it's not the most intuitive thing to think of if you don't happen to know that.

I believe choco with no arguments is parsed by some tools that use Chocolatey, so I'm not sure about that one.

**Comment by TeaDrivenDev** [comment]
Point taken. What about adding a `help` command as an alias for `/?`? That would be in line with the usual command style and probably the first thing many people try if they've ever seen a Chocolatey command line before. (Okay, separate issue then, I guess.)

**Comment by ferventcoder** [comment]
Created #944. I thought I had an issue created for that. It looks like it was in my reminders list to create an issue for a "help" command.

**Comment by ferventcoder** [comment]
Will provide a more actionable message in 0.10.1.
