### ISSUE TITLE
Packages with static URLs are broken under the stricter checksum rules

### ISSUE THREAD

**Issue by AnthonyMastrean** [chocolatey/choco#990]
Packages with static URLs have always been a pain. That is, packages that publish their installer/binaries without the version in the URL.

```
http://example.com/foo.msi
```

With the stricter checksum rules in effect, it seems like this problem is going to get worse. You could create an automatic package if the version is somewhere else in the domain (on the download page somewhere, for example).

But, I'm not sure that casual package maintainers are going to necessarily go through with that.

Do we have any other ideas about how to deal with static URLs?

**Comment by ferventcoder** [comment]
I'm guessing you didn't receive the maintainer communications that were sent out last month. They specifically addressed this situation and the options that are available.

Since I see your name is on that list, it may have went into your spam filter or it may have hit one of your filters. Search for "Chocolatey Community Package Maintainers" as part of the subject.

Also you can read them here - http://us8.campaign-archive1.com/home/?u=86a6d80146a0da7f2223712e4&id=3cf9038d77

**Comment by ferventcoder** [comment]
Feel free to hop into gitter chat if you want to discuss further.
